
#include <iostream>

#include "eurovision.h"

using std::cout;
using std::endl;
#include <fstream>
using std::ifstream;
using std::ofstream;
using std::cerr;
using std::endl;


void TEST4() {
    ofstream to("../test4myresult.txt");
    MainControl eurovision;
    Participant p1("andora","song_andora",109,"singer_andora");
    to<<p1<<endl;
    Participant p2("greece","song_greece",205,"singer_greece");
    to<<p2<<endl;
    Participant p3("serbia","song_serbia",170,"singer_serbia");
    to<<p3<<endl;
    Participant p4("hungary","song_hungary",161,"singer_hungary");
    to<<p4<<endl;
    Participant p5("austria","song_austria",212,"singer_austria");
    to<<p5<<endl;
    Participant p6("russia","song_russia",126,"singer_russia");
    to<<p6<<endl;
    Participant p7("switzerland","song_switzerland",223,"singer_switzerland");
    to<<p7<<endl;
    Participant p8("ukraine","song_ukraine",107,"singer_ukraine");
    to<<p8<<endl;
    Participant p9("spain","song_spain",101,"singer_spain");
    to<<p9<<endl;
    Participant p10("cyrpus","song_cyrpus",173,"singer_cyrpus");
    to<<p10<<endl;
    Participant p11("russia","song_russia",122,"singer_russia");
    to<<p11<<endl;
    Participant p12("bulgaria","song_bulgaria",139,"singer_bulgaria");
    to<<p12<<endl;
    Participant p13("netherlands","song_netherlands",157,"singer_netherlands");
    to<<p13<<endl;
    Participant p14("ukraine","song_ukraine",163,"singer_ukraine");
    to<<p14<<endl;
    Participant p15("france","song_france",128,"singer_france");
    to<<p15<<endl;
    Participant p16("belarus","song_belarus",220,"singer_belarus");
    to<<p16<<endl;
    Participant p17("germany","song_germany",171,"singer_germany");
    to<<p17<<endl;
    Participant p18("moldova","song_moldova",127,"singer_moldova");
    to<<p18<<endl;
    Participant p19("bulgaria","song_bulgaria",109,"singer_bulgaria");
    to<<p19<<endl;
    Participant p20("norway","song_norway",151,"singer_norway");
    to<<p20<<endl;
    Participant p21("slovakia","song_slovakia",125,"singer_slovakia");
    to<<p21<<endl;
    Participant p22("bulgaria","song_bulgaria",226,"singer_bulgaria");
    to<<p22<<endl;
    Participant p23("luxembourg","song_luxembourg",163,"singer_luxembourg");
    to<<p23<<endl;
    Participant p24("hungary","song_hungary",165,"singer_hungary");
    to<<p24<<endl;
    Participant p25("lithiania","song_lithiania",107,"singer_lithiania");
    to<<p25<<endl;
    Participant p26("georgia","song_georgia",114,"singer_georgia");
    to<<p26<<endl;
    Participant p27("moldova","song_moldova",151,"singer_moldova");
    to<<p27<<endl;
    Participant p28("italy","song_italy",203,"singer_italy");
    to<<p28<<endl;
    Participant p29("germany","song_germany",128,"singer_germany");
    to<<p29<<endl;
    Participant p30("france","song_france",128,"singer_france");
    to<<p30<<endl;
    Participant p31("ireland","song_ireland",198,"singer_ireland");
    to<<p31<<endl;
    Participant p32("slovenia","song_slovenia",121,"singer_slovenia");
    to<<p32<<endl;
    Participant p33("norway","song_norway",140,"singer_norway");
    to<<p33<<endl;
    Participant p34("moldova","song_moldova",179,"singer_moldova");
    to<<p34<<endl;
    Participant p35("bosnia","song_bosnia",167,"singer_bosnia");
    to<<p35<<endl;
    Participant p36("belgium","song_belgium",144,"singer_belgium");
    to<<p36<<endl;
    p8.update("new_song",0,"");
    p30.update("new_song",0,"");
    p11.update("new_song",0,"");
    p1.update("new_song",0,"");
    p33.update("new_song",0,"newsinger");
    p24.update("new_song",0,"newsinger");
    p22.update("new_song",0,"newsinger");
    p21.update("new_song",0,"newsinger");
    p36.update("new_song",102,"newsinger");
    p12.update("new_song",189,"newsinger");
    p18.update("new_song",117,"newsinger");
    p14.update("new_song",158,"newsinger");
    to<<eurovision<<endl;
    eurovision+=p3;
    eurovision+=p35;
    eurovision+=p22;
    eurovision+=p20;
    eurovision+=p21;
    eurovision+=p3;
    eurovision+=p34;
    eurovision+=p33;
    eurovision+=p21;
    eurovision+=p11;
    eurovision+=p17;
    eurovision+=p3;
    eurovision+=p7;
    eurovision+=p13;
    to<<eurovision<<endl;
    eurovision-=p19;
    eurovision+=p10;
    eurovision+=p2;
    eurovision+=p24;
    eurovision+=p1;
    eurovision+=p7;
    eurovision-=p5;
    eurovision-=p6;
    eurovision+=p15;
    eurovision-=p8;
    eurovision+=p12;
    eurovision-=p3;
    eurovision-=p15;
    eurovision-=p5;
    eurovision+=p10;
    eurovision-=p22;
    eurovision-=p26;
    eurovision+=p30;
    eurovision-=p18;
    eurovision+=p13;
    eurovision-=p33;
    eurovision+=p33;
    eurovision+=p4;
    eurovision+=p20;
    to<<eurovision<<endl;
    (((((((((((((eurovision-=p6)+=p1)+=p8)-=p35)-=p25)-=p29)-=p9)+=p3)-=p15)
    +=p18)-=p31)+=p24)
    +=p36)+=p22;
    MainControl::Iterator i;
    for (i = eurovision.begin(); i<eurovision.end(); ++i)
        to << *i << endl;
    for (i = eurovision.begin(); !(i==eurovision.end()); ++i)
        to << *i << endl;
    eurovision.setPhase(Contest);
    eurovision.setPhase(Voting);
    eurovision.participate("malta");
    eurovision.participate("moldova");
    eurovision.participate("belarus");
    eurovision.participate("italy");
    eurovision.participate("germany");
    eurovision.participate("luxembourg");
    eurovision.participate("israel");
    eurovision.participate("germany");
    eurovision.participate("germany");
    eurovision.participate("france");
    eurovision.participate("austria");
    eurovision.participate("malta");
    eurovision.participate("austria");
    eurovision.participate("uk");
    p4.update("",120,"");
    to<<p4<<endl;
    p9.update("",120,"");
    to<<p9<<endl;
    p26.update("",120,"");
    to<<p26<<endl;
    p30.update("",120,"");
    to<<p30<<endl;
    p10.update("",120,"");
    to<<p10<<endl;
    p13.update("",120,"");
    to<<p13<<endl;
    p26.update("",120,"");
    to<<p26<<endl;
    p3.update("",120,"");
    to<<p3<<endl;
    p2.update("",120,"");
    to<<p2<<endl;
    p11.update("",120,"");
    to<<p11<<endl;
    p8.update("",120,"");
    to<<p8<<endl;
    p6.update("",120,"");
    to<<p6<<endl;
    p34.update("",120,"");
    to<<p34<<endl;
    p7.update("",120,"");
    to<<p7<<endl;
    Voter v1("latvia",Regular);
    Voter v2("armenia",Judge);
    Voter v3("slovakia",Regular);
    Voter v4("serbia",Judge);
    Voter v5("estonia",Regular);
    Voter v6("norway",Judge);
    Voter v7("croatia");
    Voter v8("austria",Judge);
    Voter v9("slovenia",Regular);
    Voter v10("croatia",Regular);
    Voter v11("bulgaria",Judge);
    Voter v12("georgia",Judge);
    Voter v13("bosnia");
    Voter v14("ireland",Judge);
    Voter v15("georgia");
    Voter v16("israel");
    Voter v17("cyrpus",Regular);
    Voter v18("estonia",Regular);
    Voter v19("switzerland");
    Voter v20("austria");
    Voter v21("norway");
    Voter v22("armenia");
    Voter v23("croatia",Judge);
    Voter v24("latvia",Judge);
    Voter v25("france",Regular);
    Voter v26("andora");
    Voter v27("netherlands",Judge);
    Voter v28("austria",Regular);
    Voter v29("andora");
    Voter v30("belgium",Regular);
    Voter v31("belgium",Regular);
    Voter v32("slovakia");
    Voter v33("latvia",Regular);
    Voter v34("greece");
    Voter v35("cyrpus");
    Voter v36("sweden",Regular);
    Voter v37("uk",Judge);
    Voter v38("netherlands",Regular);
    Voter v39("estonia");
    Voter v40("france",Judge);
    Voter v41("ukraine",Regular);
    Voter v42("italy",Judge);
    Voter v43("belarus",Judge);
    Voter v44("kazakhastan",Judge);
    Voter v45("france",Judge);
    Voter v46("belgium",Judge);
    Voter v47("bulgaria");
    Voter v48("norway",Judge);
    Voter v49("ireland",Judge);
    Voter v50("croatia",Regular);
    Voter v51("russia");
    Voter v52("belgium",Judge);
    Voter v53("sweden");
    Voter v54("luxembourg",Judge);
    Voter v55("switzerland");
    Voter v56("slovakia",Judge);
    Voter v57("serbia",Regular);
    Voter v58("ukraine");
    Voter v59("greece");
    Voter v60("netherlands");
    Voter v61("russia");
    Voter v62("latvia");
    Voter v63("serbia",Regular);
    Voter v64("slovenia");
    Voter v65("germany",Judge);
    Voter v66("ireland");
    Voter v67("uk");
    Voter v68("sweden",Regular);
    Voter v69("italy",Judge);
    Voter v70("netherlands");
    Voter v71("belgium",Regular);
    Voter v72("moldova",Judge);
    Voter v73("russia",Judge);
    Voter v74("austria");
    Voter v75("georgia",Regular);
    Voter v76("norway",Regular);
    Voter v77("netherlands",Regular);
    Voter v78("lithiania",Judge);
    Voter v79("uk",Regular);
    Voter v80("slovakia",Regular);
    Voter v81("belarus",Judge);
    Voter v82("estonia");
    Voter v83("belgium",Judge);
    Voter v84("luxembourg",Regular);
    Voter v85("hungary");
    Voter v86("greece",Regular);
    Voter v87("slovakia",Judge);
    Voter v88("israel",Judge);
    Voter v89("austria",Regular);
    Voter v90("netherlands");
    Voter v91("croatia");
    Voter v92("croatia",Judge);
    Voter v93("turkey",Judge);
    Voter v94("germany",Judge);
    Voter v95("russia");
    Voter v96("norway",Judge);
    Voter v97("switzerland");
    Voter v98("russia",Regular);
    Voter v99("uk",Judge);
    to<<eurovision<<endl;
    eurovision+=Vote(v55,"armenia");
    eurovision+=Vote(v7,"ukraine");
    eurovision+=Vote(v74,"bosnia");
    eurovision+=Vote(v53,"luxembourg");
    eurovision+=Vote(v23,"belarus");
    eurovision+=Vote(v59,"kazakhastan");
    eurovision+=Vote(v36,"serbia");
    eurovision+=Vote(v88,"serbia");
    eurovision+=Vote(v82,"turkey");
    eurovision+=Vote(v94,"israel","belgium","austria","cyrpus","lithiania","switzerland","armenia","georgia","slovenia");
    eurovision+=Vote(v69,"cyrpus","slovakia","malta","france");
    eurovision+=Vote(v59,"moldova");
    eurovision+=Vote(v3,"bosnia");
    eurovision+=Vote(v57,"slovakia");
    eurovision+=Vote(v83,"croatia","serbia","ireland","slovenia","bosnia","bulgaria");
    eurovision+=Vote(v70,"hungary");
    eurovision+=Vote(v91,"croatia");
    eurovision+=Vote(v18,"slovenia");
    eurovision+=Vote(v97,"luxembourg");
    eurovision+=Vote(v35,"israel");
    eurovision+=Vote(v97,"andora");
    eurovision+=Vote(v38,"lithiania");
    eurovision+=Vote(v5,"switzerland");
    eurovision+=Vote(v17,"lithiania");
    eurovision+=Vote(v76,"estonia");
    eurovision+=Vote(v96,"greece","lithiania","france","bosnia","kazakhastan","ukraine","slovenia","israel");
    eurovision+=Vote(v77,"israel");
    eurovision+=Vote(v26,"croatia");
    eurovision+=Vote(v38,"germany");
    eurovision+=Vote(v80,"switzerland");
    eurovision+=Vote(v27,"cyrpus","serbia","france","turkey","latvia","netherlands","kazakhastan","belarus","bulgaria");
    eurovision+=Vote(v82,"croatia");
    eurovision+=Vote(v4,"italy","armenia","georgia","belgium","latvia","turkey");
    eurovision+=Vote(v69,"france","italy","lithiania","latvia","switzerland","israel","georgia","moldova");
    eurovision+=Vote(v92,"moldova","italy","belgium","bulgaria","israel","slovakia","ireland","luxembourg","turkey");
    eurovision+=Vote(v95,"switzerland");
    eurovision+=Vote(v14,"andora","italy");
    eurovision+=Vote(v50,"greece");
    eurovision+=Vote(v79,"andora");
    eurovision+=Vote(v52,"turkey");
    eurovision+=Vote(v66,"serbia");
    eurovision+=Vote(v99,"armenia","croatia","andora","luxembourg","sweden","italy");
    eurovision+=Vote(v29,"latvia");
    eurovision+=Vote(v97,"ukraine");
    eurovision+=Vote(v57,"malta");
    eurovision+=Vote(v78,"malta","turkey","estonia","spain","ukraine","georgia");
    eurovision+=Vote(v30,"moldova");
    eurovision+=Vote(v48,"turkey","austria","netherlands","belgium","greece");
    eurovision+=Vote(v1,"germany");
    eurovision+=Vote(v81,"france","kazakhastan","germany","bosnia","greece","sweden","slovenia");
    eurovision+=Vote(v59,"france");
    eurovision+=Vote(v61,"serbia");
    eurovision+=Vote(v82,"kazakhastan");
    eurovision+=Vote(v15,"lithiania");
    eurovision+=Vote(v31,"armenia");
    eurovision+=Vote(v5,"georgia");
    eurovision+=Vote(v46,"andora","latvia","israel","russia");
    eurovision+=Vote(v68,"georgia");
    eurovision+=Vote(v66,"slovakia");
    eurovision+=Vote(v68,"israel");
    eurovision+=Vote(v95,"norway");
    eurovision+=Vote(v28,"kazakhastan");
    eurovision+=Vote(v31,"ukraine");
    eurovision+=Vote(v15,"hungary");
    eurovision+=Vote(v45,"malta","slovenia","slovakia","bulgaria","italy");
    eurovision+=Vote(v18,"ukraine");
    eurovision+=Vote(v42,"israel","lithiania","malta");
    eurovision+=Vote(v95,"russia");
    eurovision+=Vote(v64,"sweden");
    eurovision+=Vote(v76,"armenia");
    eurovision+=Vote(v6,"switzerland");
    eurovision+=Vote(v22,"croatia");
    eurovision+=Vote(v86,"latvia");
    eurovision+=Vote(v56,"luxembourg","ireland","turkey","netherlands","bulgaria");
    eurovision+=Vote(v84,"latvia");
    eurovision+=Vote(v45,"sweden","armenia","slovakia","germany","greece","luxembourg","serbia","austria","turkey","italy");
    eurovision+=Vote(v3,"austria");
    eurovision+=Vote(v59,"bosnia");
    eurovision+=Vote(v5,"moldova");
    eurovision+=Vote(v76,"france");
    eurovision+=Vote(v6,"slovenia","moldova","bulgaria","latvia","malta","ireland");
    eurovision+=Vote(v70,"russia");
    eurovision+=Vote(v59,"italy");
    eurovision+=Vote(v15,"malta");
    eurovision+=Vote(v41,"norway");
    eurovision+=Vote(v77,"moldova");
    eurovision+=Vote(v4,"latvia","russia","netherlands","belgium");
    eurovision+=Vote(v23,"ukraine","bosnia","luxembourg","belgium","norway","russia");
    eurovision+=Vote(v83,"slovenia","belgium","netherlands","ukraine");
    eurovision+=Vote(v38,"andora");
    eurovision+=Vote(v10,"ireland");
    eurovision+=Vote(v93,"france","serbia","russia","malta","belarus","sweden");
    eurovision+=Vote(v96,"israel","slovenia");
    eurovision+=Vote(v11,"russia","luxembourg","lithiania","germany","estonia","kazakhastan","malta");
    eurovision+=Vote(v33,"croatia");
    eurovision+=Vote(v11,"israel","moldova","georgia","armenia","austria","croatia","kazakhastan","estonia","cyrpus");
    eurovision+=Vote(v14,"germany","georgia","switzerland");
    eurovision+=Vote(v91,"latvia");
    eurovision+=Vote(v84,"ireland");
    eurovision+=Vote(v28,"norway");
    eurovision+=Vote(v62,"georgia");
    eurovision+=Vote(v71,"israel");
    eurovision+=Vote(v59,"armenia");
    eurovision+=Vote(v17,"moldova");
    eurovision+=Vote(v29,"malta");
    eurovision+=Vote(v76,"spain");
    eurovision+=Vote(v37,"ireland","austria","russia");
    eurovision+=Vote(v20,"belarus");
    eurovision+=Vote(v97,"croatia");
    eurovision+=Vote(v17,"sweden");
    eurovision+=Vote(v92,"greece");
    eurovision+=Vote(v37,"belgium","germany","latvia","italy","hungary","bulgaria","slovakia","estonia");
    eurovision+=Vote(v18,"kazakhastan");
    eurovision+=Vote(v86,"serbia");
    eurovision+=Vote(v96,"france","serbia","estonia","armenia","lithiania");
    eurovision+=Vote(v22,"italy");
    eurovision+=Vote(v65,"luxembourg","belarus","spain","netherlands","malta","latvia","slovakia");
    eurovision+=Vote(v88,"spain","belarus","netherlands","germany");
    eurovision+=Vote(v66,"kazakhastan");
    eurovision+=Vote(v78,"armenia","cyrpus");
    eurovision+=Vote(v58,"spain");
    eurovision+=Vote(v24,"belgium","austria","lithiania","israel","russia");
    eurovision+=Vote(v85,"netherlands");
    eurovision+=Vote(v65,"sweden","ukraine","netherlands","armenia","bulgaria","germany");
    eurovision+=Vote(v25,"israel");
    eurovision+=Vote(v53,"latvia");
    eurovision+=Vote(v49,"luxembourg","france","belarus","malta");
    eurovision+=Vote(v14,"andora","italy","slovakia");
    eurovision+=Vote(v39,"kazakhastan");
    eurovision+=Vote(v95,"lithiania");
    eurovision+=Vote(v18,"germany");
    eurovision+=Vote(v81,"cyrpus","slovenia","belgium","russia","georgia","turkey","belarus");
    eurovision+=Vote(v15,"lithiania");
    eurovision+=Vote(v68,"moldova");
    eurovision+=Vote(v57,"armenia");
    eurovision+=Vote(v14,"belgium");
    eurovision+=Vote(v84,"sweden");
    eurovision+=Vote(v30,"norway");
    eurovision+=Vote(v42,"ukraine","slovakia","sweden");
    eurovision+=Vote(v4,"lithiania","luxembourg","georgia","latvia","netherlands","kazakhastan","ukraine","spain","sweden");
    eurovision+=Vote(v28,"italy");
    eurovision+=Vote(v62,"ukraine");
    eurovision+=Vote(v51,"netherlands");
    eurovision+=Vote(v31,"hungary");
    eurovision+=Vote(v93,"ukraine","sweden","serbia","estonia","greece","bosnia","belgium","austria");
    eurovision+=Vote(v56,"bulgaria","norway","georgia","croatia","belgium","russia","armenia","netherlands","france");
    eurovision+=Vote(v22,"sweden");
    eurovision+=Vote(v18,"france");
    eurovision+=Vote(v76,"hungary");
    eurovision+=Vote(v3,"andora");
    eurovision+=Vote(v33,"lithiania");
    eurovision+=Vote(v5,"estonia");
    eurovision+=Vote(v66,"hungary");
    eurovision+=Vote(v4,"serbia","moldova");
    eurovision+=Vote(v84,"hungary");
    eurovision+=Vote(v1,"germany");
    eurovision+=Vote(v92,"israel","malta","belarus","belgium");
    eurovision+=Vote(v69,"italy","serbia","turkey","luxembourg","georgia","israel","moldova");
    eurovision+=Vote(v33,"serbia");
    eurovision+=Vote(v43,"bosnia","france");
    eurovision+=Vote(v16,"armenia");
    eurovision+=Vote(v37,"serbia");
    eurovision+=Vote(v2,"estonia","malta","hungary");
    eurovision+=Vote(v21,"andora");
    eurovision+=Vote(v30,"germany");
    eurovision+=Vote(v13,"andora");
    eurovision+=Vote(v46,"georgia","sweden","turkey","hungary");
    eurovision+=Vote(v19,"france");
    eurovision+=Vote(v86,"germany");
    eurovision+=Vote(v10,"georgia");
    eurovision+=Vote(v83,"russia","luxembourg","andora","cyrpus","belarus","israel","belgium","germany","croatia");
    eurovision+=Vote(v71,"armenia");
    eurovision+=Vote(v27,"latvia","andora");
    eurovision+=Vote(v97,"luxembourg");
    eurovision+=Vote(v94,"turkey","germany","malta");
    eurovision+=Vote(v85,"turkey");
    eurovision+=Vote(v45,"luxembourg","hungary","belarus","andora","lithiania","serbia","russia","malta");
    eurovision+=Vote(v62,"spain");
    eurovision+=Vote(v10,"slovakia");
    eurovision+=Vote(v58,"bulgaria");
    eurovision+=Vote(v44,"turkey","slovenia","switzerland","israel","hungary","luxembourg");
    eurovision+=Vote(v33,"bulgaria");
    eurovision+=Vote(v75,"slovakia");
    eurovision+=Vote(v61,"serbia");
    eurovision+=Vote(v48,"norway","armenia","hungary","sweden");
    eurovision+=Vote(v49,"greece","bulgaria","cyrpus","austria");
    eurovision+=Vote(v15,"germany");
    eurovision+=Vote(v64,"bosnia");
    eurovision+=Vote(v47,"latvia");
    eurovision+=Vote(v65,"croatia","spain");
    eurovision+=Vote(v59,"bulgaria");
    eurovision+=Vote(v78,"belarus","lithiania","slovenia","turkey","hungary");
    eurovision+=Vote(v80,"andora");
    eurovision+=Vote(v1,"moldova");
    eurovision+=Vote(v20,"georgia");
    eurovision+=Vote(v2,"latvia","bulgaria","slovenia","armenia","netherlands","austria","ireland");
    eurovision+=Vote(v37,"croatia","greece","serbia","netherlands","moldova","cyrpus","spain");
    eurovision+=Vote(v21,"cyrpus");
    eurovision+=Vote(v56,"kazakhastan","norway");
    p26.update("shouldnot",143,"error");
    to<<p26<<endl;
    p15.update("shouldnot",143,"error");
    to<<p15<<endl;
    p31.update("shouldnot",143,"error");
    to<<p31<<endl;
    p17.update("shouldnot",143,"error");
    to<<p17<<endl;
    p3.update("shouldnot",143,"error");
    to<<p3<<endl;
    p26.update("shouldnot",143,"error");
    to<<p26<<endl;
    p12.update("shouldnot",143,"error");
    to<<p12<<endl;
    p24.update("shouldnot",143,"error");
    to<<p24<<endl;
    p12.update("shouldnot",143,"error");
    to<<p12<<endl;
    p20.update("shouldnot",143,"error");
    to<<p20<<endl;
    p10.update("shouldnot",143,"error");
    to<<p10<<endl;
    p26.update("shouldnot",143,"error");
    to<<p26<<endl;
    p5.update("shouldnot",143,"error");
    to<<p5<<endl;
    p2.update("shouldnot",143,"error");
    to<<p2<<endl;
    to<<eurovision<<endl;
    to<<eurovision(1,Regular)<<endl;
    to<<eurovision(2,Regular)<<endl;
    to<<eurovision(3,Regular)<<endl;
    to<<eurovision(4,Regular)<<endl;
    to<<eurovision(5,Regular)<<endl;
    to<<eurovision(6,Regular)<<endl;
    to<<eurovision(7,Regular)<<endl;
    to<<eurovision(8,Regular)<<endl;
    to<<eurovision(9,Regular)<<endl;
    to<<eurovision(10,Regular)<<endl;
    to<<eurovision(1,Judge)<<endl;
    to<<eurovision(2,Judge)<<endl;
    to<<eurovision(3,Judge)<<endl;
    to<<eurovision(4,Judge)<<endl;
    to<<eurovision(5,Judge)<<endl;
    to<<eurovision(6,Judge)<<endl;
    to<<eurovision(7,Judge)<<endl;
    to<<eurovision(8,Judge)<<endl;
    to<<eurovision(9,Judge)<<endl;
    to<<eurovision(10,Judge)<<endl;
    to<<eurovision(1,All)<<endl;
    to<<eurovision(2,All)<<endl;
    to<<eurovision(3,All)<<endl;
    to<<eurovision(4,All)<<endl;
    to<<eurovision(5,All)<<endl;
    to<<eurovision(6,All)<<endl;
    to<<eurovision(7,All)<<endl;
    to<<eurovision(8,All)<<endl;
    to<<eurovision(9,All)<<endl;
    to<<eurovision(10,All)<<endl;
    to<<eurovision<<endl;

}