
#include <iostream>

#include "eurovision.h"

using std::cout;
using std::endl;
#include <fstream>
using std::ifstream;
using std::ofstream;
using std::cerr;
using std::endl;


void TEST7() {
    ofstream to("../test7myresult.txt");
    MainControl eurovision;
    Participant p1("slovenia","song_slovenia",193,"singer_slovenia");
    to<<p1<<endl;
    Participant p2("uk","song_uk",152,"singer_uk");
    to<<p2<<endl;
    Participant p3("croatia","song_croatia",220,"singer_croatia");
    to<<p3<<endl;
    Participant p4("belarus","song_belarus",130,"singer_belarus");
    to<<p4<<endl;
    Participant p5("turkey","song_turkey",122,"singer_turkey");
    to<<p5<<endl;
    Participant p6("spain","song_spain",159,"singer_spain");
    to<<p6<<endl;
    Participant p7("armenia","song_armenia",159,"singer_armenia");
    to<<p7<<endl;
    Participant p8("cyrpus","song_cyrpus",220,"singer_cyrpus");
    to<<p8<<endl;
    Participant p9("germany","song_germany",166,"singer_germany");
    to<<p9<<endl;
    Participant p10("norway","song_norway",153,"singer_norway");
    to<<p10<<endl;
    Participant p11("sweden","song_sweden",107,"singer_sweden");
    to<<p11<<endl;
    Participant p12("hungary","song_hungary",194,"singer_hungary");
    to<<p12<<endl;
    Participant p13("norway","song_norway",215,"singer_norway");
    to<<p13<<endl;
    Participant p14("russia","song_russia",110,"singer_russia");
    to<<p14<<endl;
    Participant p15("moldova","song_moldova",178,"singer_moldova");
    to<<p15<<endl;
    Participant p16("greece","song_greece",115,"singer_greece");
    to<<p16<<endl;
    Participant p17("armenia","song_armenia",187,"singer_armenia");
    to<<p17<<endl;
    Participant p18("malta","song_malta",158,"singer_malta");
    to<<p18<<endl;
    Participant p19("france","song_france",130,"singer_france");
    to<<p19<<endl;
    Participant p20("ukraine","song_ukraine",164,"singer_ukraine");
    to<<p20<<endl;
    Participant p21("kazakhastan","song_kazakhastan",214,"singer_kazakhastan");
    to<<p21<<endl;
    Participant p22("belgium","song_belgium",125,"singer_belgium");
    to<<p22<<endl;
    Participant p23("russia","song_russia",117,"singer_russia");
    to<<p23<<endl;
    Participant p24("italy","song_italy",116,"singer_italy");
    to<<p24<<endl;
    Participant p25("belgium","song_belgium",188,"singer_belgium");
    to<<p25<<endl;
    Participant p26("malta","song_malta",139,"singer_malta");
    to<<p26<<endl;
    Participant p27("ireland","song_ireland",124,"singer_ireland");
    to<<p27<<endl;
    Participant p28("turkey","song_turkey",120,"singer_turkey");
    to<<p28<<endl;
    Participant p29("cyrpus","song_cyrpus",218,"singer_cyrpus");
    to<<p29<<endl;
    Participant p30("spain","song_spain",215,"singer_spain");
    to<<p30<<endl;
    Participant p31("kazakhastan","song_kazakhastan",152,"singer_kazakhastan");
    to<<p31<<endl;
    Participant p32("cyrpus","song_cyrpus",111,"singer_cyrpus");
    to<<p32<<endl;
    Participant p33("kazakhastan","song_kazakhastan",154,"singer_kazakhastan");
    to<<p33<<endl;
    Participant p34("belarus","song_belarus",172,"singer_belarus");
    to<<p34<<endl;
    Participant p35("netherlands","song_netherlands",122,"singer_netherlands");
    to<<p35<<endl;
    Participant p36("israel","song_israel",142,"singer_israel");
    to<<p36<<endl;
    p36.update("new_song",0,"");
    p19.update("new_song",0,"");
    p21.update("new_song",0,"");
    p12.update("new_song",0,"");
    p8.update("new_song",0,"newsinger");
    p30.update("new_song",0,"newsinger");
    p28.update("new_song",0,"newsinger");
    p24.update("new_song",0,"newsinger");
    p16.update("new_song",112,"newsinger");
    p20.update("new_song",114,"newsinger");
    p13.update("new_song",157,"newsinger");
    p2.update("new_song",131,"newsinger");
    to<<eurovision<<endl;
    eurovision+=p30;
    eurovision+=p6;
    eurovision+=p21;
    eurovision+=p12;
    eurovision+=p33;
    eurovision+=p1;
    eurovision+=p9;
    eurovision+=p33;
    eurovision+=p15;
    eurovision+=p25;
    eurovision+=p15;
    eurovision+=p3;
    eurovision+=p29;
    eurovision+=p19;
    to<<eurovision<<endl;
    eurovision+=p15;
    eurovision-=p1;
    eurovision-=p9;
    eurovision+=p30;
    eurovision-=p35;
    eurovision-=p4;
    eurovision+=p16;
    eurovision+=p25;
    eurovision-=p10;
    eurovision-=p23;
    eurovision-=p4;
    eurovision+=p7;
    eurovision+=p8;
    eurovision-=p31;
    eurovision+=p23;
    eurovision-=p35;
    eurovision-=p9;
    eurovision+=p33;
    eurovision+=p34;
    eurovision+=p27;
    eurovision-=p23;
    eurovision+=p25;
    eurovision+=p33;
    eurovision+=p33;
    to<<eurovision<<endl;
    ((((((eurovision+=p29)+=p35)+=p35)-=p35)-=p26)-=p10)-=p18;
    MainControl::Iterator i;
    for (i = eurovision.begin(); i<eurovision.end(); ++i)
        to << *i << endl;
    for (i = eurovision.begin(); !(i==eurovision.end()); ++i)
        to << *i << endl;
    eurovision.setPhase(Contest);
    eurovision.setPhase(Voting);
    eurovision.participate("norway");
    eurovision.participate("germany");
    eurovision.participate("switzerland");
    eurovision.participate("serbia");
    eurovision.participate("bulgaria");
    eurovision.participate("spain");
    eurovision.participate("armenia");
    eurovision.participate("malta");
    eurovision.participate("andora");
    eurovision.participate("bulgaria");
    eurovision.participate("belgium");
    eurovision.participate("cyrpus");
    eurovision.participate("estonia");
    eurovision.participate("spain");
    p33.update("",120,"");
    to<<p33<<endl;
    p10.update("",120,"");
    to<<p10<<endl;
    p7.update("",120,"");
    to<<p7<<endl;
    p32.update("",120,"");
    to<<p32<<endl;
    p27.update("",120,"");
    to<<p27<<endl;
    p6.update("",120,"");
    to<<p6<<endl;
    p31.update("",120,"");
    to<<p31<<endl;
    p35.update("",120,"");
    to<<p35<<endl;
    p22.update("",120,"");
    to<<p22<<endl;
    p4.update("",120,"");
    to<<p4<<endl;
    p25.update("",120,"");
    to<<p25<<endl;
    p3.update("",120,"");
    to<<p3<<endl;
    p9.update("",120,"");
    to<<p9<<endl;
    p11.update("",120,"");
    to<<p11<<endl;
    Voter v1("croatia",Judge);
    Voter v2("luxembourg",Judge);
    Voter v3("norway",Regular);
    Voter v4("belgium");
    Voter v5("cyrpus",Judge);
    Voter v6("estonia");
    Voter v7("sweden",Regular);
    Voter v8("netherlands",Judge);
    Voter v9("bulgaria");
    Voter v10("italy",Judge);
    Voter v11("belgium",Regular);
    Voter v12("moldova",Regular);
    Voter v13("cyrpus");
    Voter v14("kazakhastan",Regular);
    Voter v15("russia",Regular);
    Voter v16("kazakhastan",Regular);
    Voter v17("sweden");
    Voter v18("turkey");
    Voter v19("ireland",Regular);
    Voter v20("moldova",Judge);
    Voter v21("slovakia",Regular);
    Voter v22("greece",Regular);
    Voter v23("france");
    Voter v24("norway",Judge);
    Voter v25("kazakhastan",Regular);
    Voter v26("bosnia");
    Voter v27("turkey",Judge);
    Voter v28("sweden");
    Voter v29("spain",Regular);
    Voter v30("sweden");
    Voter v31("uk",Judge);
    Voter v32("ukraine",Judge);
    Voter v33("france",Regular);
    Voter v34("georgia",Regular);
    Voter v35("estonia",Regular);
    Voter v36("armenia",Regular);
    Voter v37("estonia",Judge);
    Voter v38("cyrpus",Regular);
    Voter v39("serbia",Regular);
    Voter v40("andora");
    Voter v41("luxembourg",Regular);
    Voter v42("ukraine");
    Voter v43("bulgaria");
    Voter v44("uk",Regular);
    Voter v45("georgia",Regular);
    Voter v46("italy",Regular);
    Voter v47("bosnia");
    Voter v48("bosnia",Regular);
    Voter v49("russia",Regular);
    Voter v50("spain",Judge);
    Voter v51("armenia");
    Voter v52("austria");
    Voter v53("netherlands",Judge);
    Voter v54("uk",Regular);
    Voter v55("spain",Regular);
    Voter v56("spain",Judge);
    Voter v57("lithiania");
    Voter v58("belarus",Judge);
    Voter v59("moldova");
    Voter v60("cyrpus");
    Voter v61("luxembourg");
    Voter v62("bulgaria");
    Voter v63("croatia",Regular);
    Voter v64("spain",Regular);
    Voter v65("georgia");
    Voter v66("croatia",Judge);
    Voter v67("serbia",Judge);
    Voter v68("serbia",Regular);
    Voter v69("germany",Judge);
    Voter v70("uk",Regular);
    Voter v71("israel",Regular);
    Voter v72("estonia",Regular);
    Voter v73("bulgaria");
    Voter v74("malta",Judge);
    Voter v75("netherlands",Judge);
    Voter v76("austria");
    Voter v77("estonia");
    Voter v78("switzerland",Judge);
    Voter v79("belgium",Judge);
    Voter v80("israel",Judge);
    Voter v81("armenia");
    Voter v82("belarus",Judge);
    Voter v83("slovakia",Regular);
    Voter v84("slovakia",Judge);
    Voter v85("germany",Judge);
    Voter v86("hungary");
    Voter v87("serbia");
    Voter v88("serbia",Regular);
    Voter v89("netherlands",Regular);
    Voter v90("georgia",Judge);
    Voter v91("bulgaria",Judge);
    Voter v92("georgia",Regular);
    Voter v93("moldova");
    Voter v94("spain");
    Voter v95("kazakhastan",Judge);
    Voter v96("lithiania",Regular);
    Voter v97("belarus",Judge);
    Voter v98("serbia");
    Voter v99("spain");
    to<<eurovision<<endl;
    eurovision+=Vote(v86,"israel");
    eurovision+=Vote(v48,"latvia");
    eurovision+=Vote(v23,"israel");
    eurovision+=Vote(v94,"croatia");
    eurovision+=Vote(v39,"italy");
    eurovision+=Vote(v93,"germany");
    eurovision+=Vote(v69,"spain","sweden","ireland");
    eurovision+=Vote(v73,"andora");
    eurovision+=Vote(v20,"netherlands","slovakia","bosnia","serbia","austria");
    eurovision+=Vote(v31,"germany","slovakia","malta","georgia","ireland");
    eurovision+=Vote(v87,"serbia");
    eurovision+=Vote(v19,"ukraine");
    eurovision+=Vote(v82,"estonia","israel","slovakia","belgium","austria","bulgaria","netherlands","georgia","germany","norway");
    eurovision+=Vote(v9,"turkey");
    eurovision+=Vote(v81,"netherlands");
    eurovision+=Vote(v3,"armenia");
    eurovision+=Vote(v97,"italy","germany","greece","israel","malta","russia","moldova");
    eurovision+=Vote(v39,"estonia");
    eurovision+=Vote(v26,"turkey");
    eurovision+=Vote(v77,"armenia");
    eurovision+=Vote(v42,"bosnia");
    eurovision+=Vote(v11,"spain");
    eurovision+=Vote(v17,"malta");
    eurovision+=Vote(v21,"luxembourg");
    eurovision+=Vote(v69,"austria","switzerland","italy","netherlands","slovenia","georgia","slovakia");
    eurovision+=Vote(v53,"latvia","estonia","moldova","france","luxembourg");
    eurovision+=Vote(v31,"moldova","slovenia","ukraine","armenia");
    eurovision+=Vote(v69,"bulgaria","kazakhastan","moldova");
    eurovision+=Vote(v13,"estonia");
    eurovision+=Vote(v57,"ireland");
    eurovision+=Vote(v68,"armenia");
    eurovision+=Vote(v57,"kazakhastan");
    eurovision+=Vote(v27,"lithiania");
    eurovision+=Vote(v59,"slovakia");
    eurovision+=Vote(v94,"france");
    eurovision+=Vote(v30,"belgium");
    eurovision+=Vote(v56,"slovenia","serbia","bulgaria","cyrpus");
    eurovision+=Vote(v10,"netherlands","slovenia","italy","estonia");
    eurovision+=Vote(v35,"greece");
    eurovision+=Vote(v80,"kazakhastan","netherlands","bulgaria","latvia");
    eurovision+=Vote(v1,"estonia","germany","italy","armenia","switzerland","spain");
    eurovision+=Vote(v96,"andora");
    eurovision+=Vote(v36,"armenia");
    eurovision+=Vote(v73,"serbia");
    eurovision+=Vote(v33,"greece");
    eurovision+=Vote(v33,"croatia");
    eurovision+=Vote(v71,"slovenia");
    eurovision+=Vote(v89,"sweden");
    eurovision+=Vote(v6,"switzerland");
    eurovision+=Vote(v16,"croatia");
    eurovision+=Vote(v13,"netherlands");
    eurovision+=Vote(v83,"turkey");
    eurovision+=Vote(v47,"bulgaria");
    eurovision+=Vote(v58,"kazakhastan","belgium","armenia","serbia","norway","estonia");
    eurovision+=Vote(v40,"spain");
    eurovision+=Vote(v37,"greece","cyrpus","spain");
    eurovision+=Vote(v46,"moldova");
    eurovision+=Vote(v59,"netherlands");
    eurovision+=Vote(v57,"norway");
    eurovision+=Vote(v97,"luxembourg","belgium","croatia","kazakhastan","hungary","latvia","cyrpus","norway");
    eurovision+=Vote(v37,"turkey","kazakhastan");
    eurovision+=Vote(v22,"belarus");
    eurovision+=Vote(v47,"belarus");
    eurovision+=Vote(v1,"bulgaria");
    eurovision+=Vote(v13,"russia");
    eurovision+=Vote(v74,"switzerland");
    eurovision+=Vote(v11,"greece");
    eurovision+=Vote(v83,"norway");
    eurovision+=Vote(v23,"malta");
    eurovision+=Vote(v27,"serbia","moldova");
    eurovision+=Vote(v85,"turkey");
    eurovision+=Vote(v19,"kazakhastan");
    eurovision+=Vote(v23,"luxembourg");
    eurovision+=Vote(v84,"netherlands","hungary","armenia","italy","croatia","switzerland");
    eurovision+=Vote(v91,"serbia","sweden","belgium","lithiania");
    eurovision+=Vote(v78,"moldova","ireland","israel","sweden","greece","italy");
    eurovision+=Vote(v26,"austria");
    eurovision+=Vote(v56,"georgia");
    eurovision+=Vote(v51,"germany");
    eurovision+=Vote(v95,"kazakhastan","andora","belgium","norway");
    eurovision+=Vote(v2,"cyrpus");
    eurovision+=Vote(v36,"france");
    eurovision+=Vote(v61,"hungary");
    eurovision+=Vote(v42,"russia");
    eurovision+=Vote(v71,"belgium");
    eurovision+=Vote(v60,"luxembourg");
    eurovision+=Vote(v95,"belarus","germany","belgium","ukraine","bulgaria","latvia","slovenia");
    eurovision+=Vote(v95,"ireland","spain","belarus","slovenia");
    eurovision+=Vote(v66,"spain","germany","russia","austria","italy","luxembourg");
    eurovision+=Vote(v70,"greece");
    eurovision+=Vote(v24,"netherlands","russia","germany","lithiania");
    eurovision+=Vote(v64,"switzerland");
    eurovision+=Vote(v76,"france");
    eurovision+=Vote(v85,"ireland","spain","moldova","malta","slovakia");
    eurovision+=Vote(v9,"cyrpus");
    eurovision+=Vote(v1,"norway","moldova","kazakhastan","belgium","france","georgia","luxembourg","ireland");
    eurovision+=Vote(v78,"bosnia");
    eurovision+=Vote(v19,"germany");
    eurovision+=Vote(v39,"ireland");
    eurovision+=Vote(v98,"georgia");
    eurovision+=Vote(v67,"belgium","slovenia","netherlands","luxembourg","italy","greece");
    eurovision+=Vote(v93,"latvia");
    eurovision+=Vote(v58,"france","slovenia");
    eurovision+=Vote(v19,"france");
    eurovision+=Vote(v11,"bosnia");
    eurovision+=Vote(v86,"slovakia");
    eurovision+=Vote(v45,"norway");
    eurovision+=Vote(v51,"croatia");
    eurovision+=Vote(v46,"israel");
    eurovision+=Vote(v35,"cyrpus");
    eurovision+=Vote(v69,"ukraine","spain","latvia","austria","cyrpus","lithiania");
    eurovision+=Vote(v95,"kazakhastan","spain","sweden");
    eurovision+=Vote(v23,"serbia");
    eurovision+=Vote(v92,"cyrpus");
    eurovision+=Vote(v21,"kazakhastan");
    eurovision+=Vote(v62,"estonia");
    eurovision+=Vote(v17,"slovenia");
    eurovision+=Vote(v16,"cyrpus");
    eurovision+=Vote(v10,"netherlands","bulgaria","slovakia","cyrpus","switzerland","turkey");
    eurovision+=Vote(v88,"bulgaria");
    eurovision+=Vote(v12,"latvia");
    eurovision+=Vote(v90,"ireland","kazakhastan","hungary","russia","belarus","bulgaria","italy");
    eurovision+=Vote(v18,"france");
    eurovision+=Vote(v3,"slovenia");
    eurovision+=Vote(v26,"croatia");
    eurovision+=Vote(v84,"lithiania","hungary","israel","ireland","cyrpus","croatia","estonia","ukraine");
    eurovision+=Vote(v3,"lithiania");
    eurovision+=Vote(v93,"estonia");
    eurovision+=Vote(v60,"spain");
    eurovision+=Vote(v76,"estonia");
    eurovision+=Vote(v58,"slovenia","croatia","italy","hungary","latvia","belarus");
    eurovision+=Vote(v92,"netherlands");
    eurovision+=Vote(v70,"bosnia");
    eurovision+=Vote(v2,"belarus","belgium","lithiania","moldova","luxembourg","netherlands","italy","sweden");
    eurovision+=Vote(v9,"netherlands");
    eurovision+=Vote(v90,"belarus","israel","greece","switzerland","netherlands","cyrpus","austria","hungary","spain","moldova");
    eurovision+=Vote(v3,"moldova");
    eurovision+=Vote(v58,"austria","bosnia","ukraine","spain","armenia");
    eurovision+=Vote(v1,"moldova","malta","germany","turkey","hungary","estonia");
    eurovision+=Vote(v60,"moldova");
    eurovision+=Vote(v18,"armenia");
    eurovision+=Vote(v96,"kazakhastan");
    eurovision+=Vote(v65,"andora");
    eurovision+=Vote(v83,"serbia");
    eurovision+=Vote(v55,"bulgaria");
    eurovision+=Vote(v45,"russia");
    eurovision+=Vote(v5,"netherlands","armenia","belarus");
    eurovision+=Vote(v18,"greece");
    eurovision+=Vote(v35,"bulgaria");
    eurovision+=Vote(v84,"israel","estonia","ireland");
    eurovision+=Vote(v24,"bulgaria","kazakhastan");
    eurovision+=Vote(v67,"estonia","ireland","lithiania","russia","armenia","spain");
    eurovision+=Vote(v54,"belarus");
    eurovision+=Vote(v20,"israel","sweden","lithiania","georgia","netherlands");
    eurovision+=Vote(v15,"croatia");
    eurovision+=Vote(v53,"georgia","luxembourg","germany","turkey");
    eurovision+=Vote(v39,"france");
    eurovision+=Vote(v47,"russia");
    eurovision+=Vote(v56,"andora","austria","serbia","armenia","georgia");
    eurovision+=Vote(v77,"ukraine");
    eurovision+=Vote(v99,"armenia");
    eurovision+=Vote(v2,"slovenia");
    eurovision+=Vote(v98,"kazakhastan");
    eurovision+=Vote(v29,"lithiania");
    eurovision+=Vote(v36,"luxembourg");
    eurovision+=Vote(v27,"france","sweden","italy","serbia");
    eurovision+=Vote(v77,"malta");
    eurovision+=Vote(v59,"andora");
    eurovision+=Vote(v8,"israel","italy","estonia","norway","luxembourg","france","serbia","germany");
    eurovision+=Vote(v64,"belgium");
    eurovision+=Vote(v61,"slovenia");
    eurovision+=Vote(v94,"russia");
    eurovision+=Vote(v84,"hungary","netherlands","armenia","france","croatia","georgia","serbia");
    eurovision+=Vote(v90,"russia","serbia","moldova","greece");
    eurovision+=Vote(v92,"greece");
    eurovision+=Vote(v22,"switzerland");
    eurovision+=Vote(v70,"greece");
    eurovision+=Vote(v59,"andora");
    eurovision+=Vote(v9,"belarus");
    eurovision+=Vote(v51,"turkey");
    eurovision+=Vote(v35,"netherlands");
    eurovision+=Vote(v1,"andora","ireland","switzerland","estonia","norway","israel");
    eurovision+=Vote(v13,"armenia");
    eurovision+=Vote(v46,"latvia");
    eurovision+=Vote(v69,"latvia","ireland","malta","estonia","moldova","georgia","ukraine","sweden");
    eurovision+=Vote(v23,"lithiania");
    eurovision+=Vote(v19,"cyrpus");
    eurovision+=Vote(v42,"serbia");
    eurovision+=Vote(v72,"hungary");
    eurovision+=Vote(v71,"armenia");
    eurovision+=Vote(v44,"latvia");
    eurovision+=Vote(v72,"cyrpus");
    eurovision+=Vote(v5,"belarus","israel","spain","greece","lithiania","andora","ireland","sweden");
    eurovision+=Vote(v10,"austria","croatia","russia","belgium");
    eurovision+=Vote(v84,"austria","france","georgia");
    eurovision+=Vote(v56,"serbia","norway","switzerland");
    eurovision+=Vote(v87,"sweden");
    eurovision+=Vote(v38,"georgia");
    eurovision+=Vote(v59,"belarus");
    p7.update("shouldnot",143,"error");
    to<<p7<<endl;
    p25.update("shouldnot",143,"error");
    to<<p25<<endl;
    p33.update("shouldnot",143,"error");
    to<<p33<<endl;
    p30.update("shouldnot",143,"error");
    to<<p30<<endl;
    p17.update("shouldnot",143,"error");
    to<<p17<<endl;
    p4.update("shouldnot",143,"error");
    to<<p4<<endl;
    p35.update("shouldnot",143,"error");
    to<<p35<<endl;
    p10.update("shouldnot",143,"error");
    to<<p10<<endl;
    p28.update("shouldnot",143,"error");
    to<<p28<<endl;
    p22.update("shouldnot",143,"error");
    to<<p22<<endl;
    p13.update("shouldnot",143,"error");
    to<<p13<<endl;
    p8.update("shouldnot",143,"error");
    to<<p8<<endl;
    p10.update("shouldnot",143,"error");
    to<<p10<<endl;
    p8.update("shouldnot",143,"error");
    to<<p8<<endl;
    to<<eurovision<<endl;
    to<<eurovision(1,Regular)<<endl;
    to<<eurovision(2,Regular)<<endl;
    to<<eurovision(3,Regular)<<endl;
    to<<eurovision(4,Regular)<<endl;
    to<<eurovision(5,Regular)<<endl;
    to<<eurovision(6,Regular)<<endl;
    to<<eurovision(7,Regular)<<endl;
    to<<eurovision(8,Regular)<<endl;
    to<<eurovision(9,Regular)<<endl;
    to<<eurovision(10,Regular)<<endl;
    to<<eurovision(1,Judge)<<endl;
    to<<eurovision(2,Judge)<<endl;
    to<<eurovision(3,Judge)<<endl;
    to<<eurovision(4,Judge)<<endl;
    to<<eurovision(5,Judge)<<endl;
    to<<eurovision(6,Judge)<<endl;
    to<<eurovision(7,Judge)<<endl;
    to<<eurovision(8,Judge)<<endl;
    to<<eurovision(9,Judge)<<endl;
    to<<eurovision(10,Judge)<<endl;
    to<<eurovision(1,All)<<endl;
    to<<eurovision(2,All)<<endl;
    to<<eurovision(3,All)<<endl;
    to<<eurovision(4,All)<<endl;
    to<<eurovision(5,All)<<endl;
    to<<eurovision(6,All)<<endl;
    to<<eurovision(7,All)<<endl;
    to<<eurovision(8,All)<<endl;
    to<<eurovision(9,All)<<endl;
    to<<eurovision(10,All)<<endl;
    to<<eurovision<<endl;

}