
#include <iostream>

#include "eurovision.h"

using std::cout;
using std::endl;
#include <fstream>
using std::ifstream;
using std::ofstream;
using std::cerr;
using std::endl;

void TEST3() {
    ofstream to("../test3myresult.txt");
    MainControl eurovision;
    Participant p1("ukraine","song_ukraine",206,"singer_ukraine");
    to<<p1<<endl;
    Participant p2("israel","song_israel",111,"singer_israel");
    to<<p2<<endl;
    Participant p3("ukraine","song_ukraine",183,"singer_ukraine");
    to<<p3<<endl;
    Participant p4("austria","song_austria",143,"singer_austria");
    to<<p4<<endl;
    Participant p5("latvia","song_latvia",200,"singer_latvia");
    to<<p5<<endl;
    Participant p6("greece","song_greece",117,"singer_greece");
    to<<p6<<endl;
    Participant p7("ireland","song_ireland",154,"singer_ireland");
    to<<p7<<endl;
    Participant p8("kazakhastan","song_kazakhastan",154,"singer_kazakhastan");
    to<<p8<<endl;
    Participant p9("greece","song_greece",153,"singer_greece");
    to<<p9<<endl;
    Participant p10("russia","song_russia",193,"singer_russia");
    to<<p10<<endl;
    Participant p11("cyrpus","song_cyrpus",144,"singer_cyrpus");
    to<<p11<<endl;
    Participant p12("estonia","song_estonia",154,"singer_estonia");
    to<<p12<<endl;
    Participant p13("armenia","song_armenia",105,"singer_armenia");
    to<<p13<<endl;
    Participant p14("kazakhastan","song_kazakhastan",169,"singer_kazakhastan");
    to<<p14<<endl;
    Participant p15("uk","song_uk",194,"singer_uk");
    to<<p15<<endl;
    Participant p16("armenia","song_armenia",111,"singer_armenia");
    to<<p16<<endl;
    Participant p17("greece","song_greece",176,"singer_greece");
    to<<p17<<endl;
    Participant p18("ireland","song_ireland",108,"singer_ireland");
    to<<p18<<endl;
    Participant p19("austria","song_austria",193,"singer_austria");
    to<<p19<<endl;
    Participant p20("israel","song_israel",192,"singer_israel");
    to<<p20<<endl;
    Participant p21("switzerland","song_switzerland",227,"singer_switzerland");
    to<<p21<<endl;
    Participant p22("switzerland","song_switzerland",214,"singer_switzerland");
    to<<p22<<endl;
    Participant p23("spain","song_spain",160,"singer_spain");
    to<<p23<<endl;
    Participant p24("croatia","song_croatia",193,"singer_croatia");
    to<<p24<<endl;
    Participant p25("slovakia","song_slovakia",124,"singer_slovakia");
    to<<p25<<endl;
    Participant p26("bulgaria","song_bulgaria",195,"singer_bulgaria");
    to<<p26<<endl;
    Participant p27("greece","song_greece",156,"singer_greece");
    to<<p27<<endl;
    Participant p28("armenia","song_armenia",165,"singer_armenia");
    to<<p28<<endl;
    Participant p29("israel","song_israel",101,"singer_israel");
    to<<p29<<endl;
    Participant p30("cyrpus","song_cyrpus",162,"singer_cyrpus");
    to<<p30<<endl;
    Participant p31("andora","song_andora",160,"singer_andora");
    to<<p31<<endl;
    Participant p32("moldova","song_moldova",230,"singer_moldova");
    to<<p32<<endl;
    Participant p33("georgia","song_georgia",185,"singer_georgia");
    to<<p33<<endl;
    Participant p34("andora","song_andora",154,"singer_andora");
    to<<p34<<endl;
    Participant p35("estonia","song_estonia",163,"singer_estonia");
    to<<p35<<endl;
    Participant p36("moldova","song_moldova",201,"singer_moldova");
    to<<p36<<endl;
    p6.update("new_song",0,"");
    p34.update("new_song",0,"");
    p21.update("new_song",0,"");
    p26.update("new_song",0,"");
    p2.update("new_song",0,"newsinger");
    p2.update("new_song",0,"newsinger");
    p15.update("new_song",0,"newsinger");
    p32.update("new_song",0,"newsinger");
    p8.update("new_song",169,"newsinger");
    p31.update("new_song",196,"newsinger");
    p5.update("new_song",189,"newsinger");
    p6.update("new_song",184,"newsinger");
    to<<eurovision<<endl;
    eurovision+=p2;
    eurovision+=p13;
    eurovision+=p8;
    eurovision+=p7;
    eurovision+=p5;
    eurovision+=p8;
    eurovision+=p19;
    eurovision+=p21;
    eurovision+=p7;
    eurovision+=p12;
    eurovision+=p26;
    eurovision+=p29;
    eurovision+=p2;
    eurovision+=p29;
    to<<eurovision<<endl;
    eurovision+=p22;
    eurovision+=p21;
    eurovision+=p18;
    eurovision+=p26;
    eurovision-=p6;
    eurovision+=p14;
    eurovision-=p30;
    eurovision+=p16;
    eurovision+=p17;
    eurovision+=p23;
    eurovision-=p28;
    eurovision+=p4;
    eurovision-=p23;
    eurovision-=p10;
    eurovision-=p12;
    eurovision-=p26;
    eurovision-=p5;
    eurovision-=p28;
    eurovision+=p6;
    eurovision+=p17;
    eurovision+=p4;
    eurovision+=p25;
    eurovision+=p23;
    eurovision+=p4;
    to<<eurovision<<endl;
    ((((((((((eurovision+=p16)+=p4)
    -=p13)-=p6)-=p32)-=p15)+=p26)-=p7)+=p33)-=p9);
    MainControl::Iterator i;
    for (i = eurovision.begin(); i<eurovision.end(); ++i)
        to << *i << endl;
    for (i = eurovision.begin(); !(i==eurovision.end()); ++i)
        to << *i << endl;
    eurovision.setPhase(Contest);
    eurovision.setPhase(Voting);
    eurovision.participate("norway");
    eurovision.participate("moldova");
    eurovision.participate("israel");
    eurovision.participate("ukraine");
    eurovision.participate("malta");
    eurovision.participate("ukraine");
    eurovision.participate("germany");
    eurovision.participate("slovenia");
    eurovision.participate("hungary");
    eurovision.participate("serbia");
    eurovision.participate("andora");
    eurovision.participate("serbia");
    eurovision.participate("ukraine");
    eurovision.participate("israel");
    p35.update("",120,"");
    to<<p35<<endl;
    p19.update("",120,"");
    to<<p19<<endl;
    p32.update("",120,"");
    to<<p32<<endl;
    p7.update("",120,"");
    to<<p7<<endl;
    p15.update("",120,"");
    to<<p15<<endl;
    p4.update("",120,"");
    to<<p4<<endl;
    p3.update("",120,"");
    to<<p3<<endl;
    p21.update("",120,"");
    to<<p21<<endl;
    p17.update("",120,"");
    to<<p17<<endl;
    p34.update("",120,"");
    to<<p34<<endl;
    p14.update("",120,"");
    to<<p14<<endl;
    p19.update("",120,"");
    to<<p19<<endl;
    p28.update("",120,"");
    to<<p28<<endl;
    p5.update("",120,"");
    to<<p5<<endl;
    Voter v1("belarus",Judge);
    Voter v2("serbia");
    Voter v3("lithiania");
    Voter v4("moldova");
    Voter v5("norway");
    Voter v6("ukraine",Judge);
    Voter v7("germany",Judge);
    Voter v8("belgium",Judge);
    Voter v9("bosnia",Regular);
    Voter v10("moldova");
    Voter v11("georgia");
    Voter v12("lithiania");
    Voter v13("croatia");
    Voter v14("sweden",Judge);
    Voter v15("germany");
    Voter v16("turkey",Judge);
    Voter v17("armenia",Regular);
    Voter v18("france",Judge);
    Voter v19("norway",Regular);
    Voter v20("malta");
    Voter v21("netherlands",Judge);
    Voter v22("turkey",Judge);
    Voter v23("uk",Regular);
    Voter v24("norway");
    Voter v25("slovakia",Judge);
    Voter v26("cyrpus",Judge);
    Voter v27("israel",Regular);
    Voter v28("slovenia",Regular);
    Voter v29("moldova");
    Voter v30("bulgaria",Judge);
    Voter v31("italy",Regular);
    Voter v32("ukraine");
    Voter v33("ukraine",Regular);
    Voter v34("serbia",Regular);
    Voter v35("switzerland",Regular);
    Voter v36("ireland");
    Voter v37("bulgaria",Regular);
    Voter v38("turkey");
    Voter v39("germany",Judge);
    Voter v40("hungary",Judge);
    Voter v41("austria",Judge);
    Voter v42("hungary");
    Voter v43("israel");
    Voter v44("hungary");
    Voter v45("hungary",Judge);
    Voter v46("bulgaria",Judge);
    Voter v47("ukraine",Regular);
    Voter v48("france");
    Voter v49("croatia");
    Voter v50("andora",Judge);
    Voter v51("greece",Judge);
    Voter v52("latvia");
    Voter v53("turkey",Regular);
    Voter v54("russia",Regular);
    Voter v55("germany");
    Voter v56("uk",Judge);
    Voter v57("austria",Judge);
    Voter v58("turkey",Regular);
    Voter v59("ukraine",Regular);
    Voter v60("serbia");
    Voter v61("belgium",Regular);
    Voter v62("latvia",Regular);
    Voter v63("slovenia");
    Voter v64("latvia",Judge);
    Voter v65("moldova");
    Voter v66("malta",Regular);
    Voter v67("netherlands",Regular);
    Voter v68("ukraine",Regular);
    Voter v69("switzerland",Regular);
    Voter v70("latvia");
    Voter v71("sweden",Judge);
    Voter v72("hungary",Regular);
    Voter v73("moldova",Regular);
    Voter v74("uk");
    Voter v75("serbia",Regular);
    Voter v76("andora",Judge);
    Voter v77("israel");
    Voter v78("turkey",Regular);
    Voter v79("lithiania");
    Voter v80("georgia");
    Voter v81("germany");
    Voter v82("uk",Regular);
    Voter v83("bulgaria");
    Voter v84("latvia",Judge);
    Voter v85("slovakia",Judge);
    Voter v86("hungary",Regular);
    Voter v87("switzerland",Regular);
    Voter v88("bulgaria",Judge);
    Voter v89("netherlands",Regular);
    Voter v90("slovakia",Regular);
    Voter v91("ireland",Judge);
    Voter v92("sweden");
    Voter v93("turkey",Judge);
    Voter v94("moldova");
    Voter v95("hungary",Regular);
    Voter v96("luxembourg",Judge);
    Voter v97("greece",Regular);
    Voter v98("russia");
    Voter v99("estonia",Regular);
    to<<eurovision<<endl;
    eurovision+=Vote(v25,"estonia","spain");
    eurovision+=Vote(v11,"malta");
    eurovision+=Vote(v11,"cyrpus");
    eurovision+=Vote(v79,"georgia");
    eurovision+=Vote(v40,"croatia","slovenia","spain","ireland","bulgaria","israel","georgia","russia","kazakhastan");
    eurovision+=Vote(v1,"luxembourg","russia","slovenia","greece","croatia","slovakia","ireland","austria");
    eurovision+=Vote(v76,"spain","bulgaria","turkey","russia","ireland","cyrpus","austria");
    eurovision+=Vote(v49,"luxembourg");
    eurovision+=Vote(v87,"germany");
    eurovision+=Vote(v54,"norway");
    eurovision+=Vote(v38,"serbia");
    eurovision+=Vote(v41,"netherlands","cyrpus","georgia","turkey","kazakhastan");
    eurovision+=Vote(v85,"spain","slovakia","andora","serbia");
    eurovision+=Vote(v15,"slovenia");
    eurovision+=Vote(v76,"croatia","ukraine","greece","austria","cyrpus","belarus");
    eurovision+=Vote(v88,"turkey","luxembourg","armenia");
    eurovision+=Vote(v6,"hungary","bosnia","belarus","luxembourg","germany");
    eurovision+=Vote(v22,"ukraine","bulgaria","bosnia");
    eurovision+=Vote(v27,"austria");
    eurovision+=Vote(v41,"moldova","belarus","france","norway","belgium","ireland","serbia");
    eurovision+=Vote(v67,"spain");
    eurovision+=Vote(v70,"sweden");
    eurovision+=Vote(v98,"cyrpus");
    eurovision+=Vote(v71,"luxembourg","hungary","belgium","georgia","andora","kazakhastan","austria","moldova");
    eurovision+=Vote(v97,"slovenia");
    eurovision+=Vote(v97,"belgium");
    eurovision+=Vote(v97,"slovakia");
    eurovision+=Vote(v28,"norway");
    eurovision+=Vote(v63,"ukraine");
    eurovision+=Vote(v38,"serbia");
    eurovision+=Vote(v76,"sweden","andora","norway","croatia","kazakhastan","italy","belarus");
    eurovision+=Vote(v73,"israel");
    eurovision+=Vote(v32,"ukraine");
    eurovision+=Vote(v70,"russia");
    eurovision+=Vote(v76,"bosnia");
    eurovision+=Vote(v49,"russia");
    eurovision+=Vote(v70,"ukraine");
    eurovision+=Vote(v39,"georgia","switzerland");
    eurovision+=Vote(v52,"israel");
    eurovision+=Vote(v28,"malta");
    eurovision+=Vote(v38,"slovenia");
    eurovision+=Vote(v53,"austria");
    eurovision+=Vote(v13,"andora");
    eurovision+=Vote(v19,"bosnia");
    eurovision+=Vote(v81,"ireland");
    eurovision+=Vote(v41,"bulgaria","netherlands","armenia","ukraine","luxembourg","slovakia","bosnia");
    eurovision+=Vote(v32,"ukraine");
    eurovision+=Vote(v24,"slovakia");
    eurovision+=Vote(v30,"slovenia","france","turkey","slovakia","lithiania","norway","latvia","greece","luxembourg");
    eurovision+=Vote(v62,"cyrpus");
    eurovision+=Vote(v30,"moldova","andora","netherlands","italy","norway","serbia","cyrpus","estonia");
    eurovision+=Vote(v62,"ireland");
    eurovision+=Vote(v87,"luxembourg");
    eurovision+=Vote(v59,"austria");
    eurovision+=Vote(v73,"turkey");
    eurovision+=Vote(v37,"switzerland");
    eurovision+=Vote(v23,"kazakhastan");
    eurovision+=Vote(v66,"bosnia");
    eurovision+=Vote(v32,"austria");
    eurovision+=Vote(v23,"france");
    eurovision+=Vote(v62,"ireland");
    eurovision+=Vote(v71,"sweden","russia","france","netherlands","luxembourg","norway");
    eurovision+=Vote(v34,"bosnia");
    eurovision+=Vote(v81,"cyrpus");
    eurovision+=Vote(v21,"russia","andora","italy","latvia","lithiania","greece","austria");
    eurovision+=Vote(v55,"spain");
    eurovision+=Vote(v30,"cyrpus");
    eurovision+=Vote(v28,"estonia");
    eurovision+=Vote(v63,"bosnia");
    eurovision+=Vote(v55,"estonia");
    eurovision+=Vote(v56,"bulgaria","switzerland","ireland");
    eurovision+=Vote(v81,"belarus");
    eurovision+=Vote(v79,"norway");
    eurovision+=Vote(v43,"sweden");
    eurovision+=Vote(v57,"sweden","luxembourg","italy","slovenia","russia","france");
    eurovision+=Vote(v33,"austria");
    eurovision+=Vote(v38,"spain");
    eurovision+=Vote(v23,"lithiania");
    eurovision+=Vote(v16,"moldova","ireland","sweden","greece","bulgaria","netherlands");
    eurovision+=Vote(v50,"bosnia","switzerland","andora","turkey","spain","ukraine","sweden","austria");
    eurovision+=Vote(v64,"serbia","hungary","greece","latvia","andora","israel","turkey");
    eurovision+=Vote(v54,"georgia");
    eurovision+=Vote(v95,"spain");
    eurovision+=Vote(v22,"luxembourg","belgium","netherlands","greece","germany");
    eurovision+=Vote(v26,"germany","ukraine","kazakhastan","france","belgium","croatia","netherlands");
    eurovision+=Vote(v35,"croatia");
    eurovision+=Vote(v30,"bosnia");
    eurovision+=Vote(v89,"andora");
    eurovision+=Vote(v2,"luxembourg");
    eurovision+=Vote(v6,"slovenia","latvia","cyrpus");
    eurovision+=Vote(v96,"cyrpus","italy","hungary","france","serbia","armenia","netherlands","luxembourg");
    eurovision+=Vote(v23,"norway");
    eurovision+=Vote(v71,"greece","hungary","estonia","georgia","bosnia","lithiania","moldova","cyrpus");
    eurovision+=Vote(v47,"georgia");
    eurovision+=Vote(v74,"greece");
    eurovision+=Vote(v53,"croatia");
    eurovision+=Vote(v21,"moldova","slovakia","kazakhastan");
    eurovision+=Vote(v92,"luxembourg");
    eurovision+=Vote(v42,"israel");
    eurovision+=Vote(v64,"lithiania","luxembourg","greece");
    eurovision+=Vote(v28,"germany");
    eurovision+=Vote(v67,"luxembourg");
    eurovision+=Vote(v13,"belgium");
    eurovision+=Vote(v96,"norway","spain","ukraine","hungary","slovenia","ireland","switzerland","israel","luxembourg");
    eurovision+=Vote(v34,"spain");
    eurovision+=Vote(v23,"russia");
    eurovision+=Vote(v41,"cyrpus","armenia","moldova","greece","sweden","estonia","france","germany");
    eurovision+=Vote(v47,"armenia");
    eurovision+=Vote(v50,"switzerland","germany","austria","latvia","andora","belarus","cyrpus");
    eurovision+=Vote(v35,"andora");
    eurovision+=Vote(v13,"kazakhastan");
    eurovision+=Vote(v38,"israel");
    eurovision+=Vote(v24,"georgia");
    eurovision+=Vote(v38,"spain");
    eurovision+=Vote(v51,"georgia","ireland","hungary","andora");
    eurovision+=Vote(v72,"luxembourg");
    eurovision+=Vote(v47,"hungary");
    eurovision+=Vote(v2,"georgia");
    eurovision+=Vote(v9,"latvia");
    eurovision+=Vote(v93,"hungary","bosnia","norway","croatia","netherlands","slovenia","bulgaria","austria","israel");
    eurovision+=Vote(v77,"italy");
    eurovision+=Vote(v17,"germany");
    eurovision+=Vote(v75,"netherlands");
    eurovision+=Vote(v29,"slovenia");
    eurovision+=Vote(v46,"slovenia","lithiania","slovakia");
    eurovision+=Vote(v56,"hungary","cyrpus","switzerland","spain");
    eurovision+=Vote(v6,"germany","russia","france","greece");
    eurovision+=Vote(v88,"kazakhastan","france","georgia","norway","croatia","moldova","ukraine");
    eurovision+=Vote(v96,"georgia","luxembourg","ireland");
    eurovision+=Vote(v55,"germany");
    eurovision+=Vote(v13,"germany");
    eurovision+=Vote(v86,"switzerland");
    eurovision+=Vote(v70,"malta");
    eurovision+=Vote(v91,"ukraine");
    eurovision+=Vote(v10,"italy");
    eurovision+=Vote(v37,"latvia");
    eurovision+=Vote(v3,"bosnia");
    eurovision+=Vote(v92,"russia");
    eurovision+=Vote(v79,"serbia");
    eurovision+=Vote(v82,"switzerland");
    eurovision+=Vote(v68,"netherlands");
    eurovision+=Vote(v21,"georgia","armenia","netherlands","switzerland","bosnia","spain","germany","cyrpus");
    eurovision+=Vote(v25,"greece","ireland","turkey","ukraine","moldova","bosnia","slovenia","latvia");
    eurovision+=Vote(v82,"belarus");
    eurovision+=Vote(v78,"bulgaria");
    eurovision+=Vote(v38,"croatia");
    eurovision+=Vote(v8,"norway","spain","kazakhastan","russia","italy");
    eurovision+=Vote(v74,"austria");
    eurovision+=Vote(v39,"israel","serbia","bulgaria","germany","lithiania","moldova","malta","netherlands");
    eurovision+=Vote(v9,"estonia");
    eurovision+=Vote(v44,"israel");
    eurovision+=Vote(v96,"ireland","estonia");
    eurovision+=Vote(v77,"slovakia");
    eurovision+=Vote(v10,"france");
    eurovision+=Vote(v27,"cyrpus");
    eurovision+=Vote(v83,"luxembourg");
    eurovision+=Vote(v93,"russia","slovenia","sweden","belgium","switzerland","germany");
    eurovision+=Vote(v39,"georgia","france","greece","croatia","armenia","hungary","bosnia","serbia");
    eurovision+=Vote(v57,"luxembourg");
    eurovision+=Vote(v90,"kazakhastan");
    eurovision+=Vote(v94,"bosnia");
    eurovision+=Vote(v42,"kazakhastan");
    eurovision+=Vote(v34,"latvia");
    eurovision+=Vote(v26,"cyrpus","ireland","turkey","belarus","luxembourg");
    eurovision+=Vote(v42,"israel");
    eurovision+=Vote(v66,"luxembourg");
    eurovision+=Vote(v24,"malta");
    eurovision+=Vote(v7,"belgium","sweden","norway","malta");
    eurovision+=Vote(v50,"croatia","france","belgium","turkey","slovakia","serbia","israel");
    eurovision+=Vote(v41,"slovakia","israel","andora");
    eurovision+=Vote(v14,"malta");
    eurovision+=Vote(v95,"israel");
    eurovision+=Vote(v96,"italy","greece","lithiania","kazakhastan","serbia","bosnia","estonia","andora");
    eurovision+=Vote(v59,"israel");
    eurovision+=Vote(v27,"austria");
    eurovision+=Vote(v13,"ukraine");
    eurovision+=Vote(v55,"hungary");
    eurovision+=Vote(v57,"serbia","austria","ukraine");
    eurovision+=Vote(v97,"armenia");
    eurovision+=Vote(v99,"hungary");
    eurovision+=Vote(v89,"israel");
    eurovision+=Vote(v77,"belarus");
    eurovision+=Vote(v84,"andora","lithiania","greece","italy","spain","russia");
    eurovision+=Vote(v29,"armenia");
    eurovision+=Vote(v95,"greece");
    eurovision+=Vote(v49,"germany");
    eurovision+=Vote(v67,"serbia");
    eurovision+=Vote(v11,"andora");
    eurovision+=Vote(v11,"germany");
    eurovision+=Vote(v63,"netherlands");
    eurovision+=Vote(v28,"slovakia");
    eurovision+=Vote(v91,"norway","belgium","slovakia");
    eurovision+=Vote(v15,"ukraine");
    eurovision+=Vote(v62,"switzerland");
    eurovision+=Vote(v17,"ireland");
    eurovision+=Vote(v31,"italy");
    eurovision+=Vote(v37,"moldova");
    eurovision+=Vote(v35,"cyrpus");
    eurovision+=Vote(v25,"slovenia","kazakhastan","netherlands","lithiania");
    p26.update("shouldnot",143,"error");
    to<<p26<<endl;
    p2.update("shouldnot",143,"error");
    to<<p2<<endl;
    p20.update("shouldnot",143,"error");
    to<<p20<<endl;
    p26.update("shouldnot",143,"error");
    to<<p26<<endl;
    p11.update("shouldnot",143,"error");
    to<<p11<<endl;
    p8.update("shouldnot",143,"error");
    to<<p8<<endl;
    p11.update("shouldnot",143,"error");
    to<<p11<<endl;
    p6.update("shouldnot",143,"error");
    to<<p6<<endl;
    p25.update("shouldnot",143,"error");
    to<<p25<<endl;
    p32.update("shouldnot",143,"error");
    to<<p32<<endl;
    p27.update("shouldnot",143,"error");
    to<<p27<<endl;
    p31.update("shouldnot",143,"error");
    to<<p31<<endl;
    p18.update("shouldnot",143,"error");
    to<<p18<<endl;
    p16.update("shouldnot",143,"error");
    to<<p16<<endl;
    to<<eurovision<<endl;
    to<<eurovision(1,Regular)<<endl;
    to<<eurovision(2,Regular)<<endl;
    to<<eurovision(3,Regular)<<endl;
    to<<eurovision(4,Regular)<<endl;
    to<<eurovision(5,Regular)<<endl;
    to<<eurovision(6,Regular)<<endl;
    to<<eurovision(7,Regular)<<endl;
    to<<eurovision(8,Regular)<<endl;
    to<<eurovision(9,Regular)<<endl;
    to<<eurovision(10,Regular)<<endl;
    to<<eurovision(1,Judge)<<endl;
    to<<eurovision(2,Judge)<<endl;
    to<<eurovision(3,Judge)<<endl;
    to<<eurovision(4,Judge)<<endl;
    to<<eurovision(5,Judge)<<endl;
    to<<eurovision(6,Judge)<<endl;
    to<<eurovision(7,Judge)<<endl;
    to<<eurovision(8,Judge)<<endl;
    to<<eurovision(9,Judge)<<endl;
    to<<eurovision(10,Judge)<<endl;
    to<<eurovision(1,All)<<endl;
    to<<eurovision(2,All)<<endl;
    to<<eurovision(3,All)<<endl;
    to<<eurovision(4,All)<<endl;
    to<<eurovision(5,All)<<endl;
    to<<eurovision(6,All)<<endl;
    to<<eurovision(7,All)<<endl;
    to<<eurovision(8,All)<<endl;
    to<<eurovision(9,All)<<endl;
    to<<eurovision(10,All)<<endl;
    to<<eurovision<<endl;

}