
#include <iostream>

#include "eurovision.h"

using std::cout;
using std::endl;
#include <fstream>
using std::ifstream;
using std::ofstream;
using std::cerr;
using std::endl;


void TEST5() {
    ofstream to("../test5myresult.txt");
    MainControl eurovision(200,22,7);
    Participant p1("greece","song_greece",209,"singer_greece");
    cout<<p1<<endl;
    Participant p2("latvia","song_latvia",171,"singer_latvia");
    cout<<p2<<endl;
    Participant p3("netherlands","song_netherlands",166,"singer_netherlands");
    cout<<p3<<endl;
    Participant p4("kazakhastan","song_kazakhastan",156,"singer_kazakhastan");
    cout<<p4<<endl;
    Participant p5("luxembourg","song_luxembourg",179,"singer_luxembourg");
    cout<<p5<<endl;
    Participant p6("italy","song_italy",146,"singer_italy");
    cout<<p6<<endl;
    Participant p7("spain","song_spain",116,"singer_spain");
    cout<<p7<<endl;
    Participant p8("hungary","song_hungary",165,"singer_hungary");
    cout<<p8<<endl;
    Participant p9("ukraine","song_ukraine",147,"singer_ukraine");
    cout<<p9<<endl;
    Participant p10("estonia","song_estonia",144,"singer_estonia");
    cout<<p10<<endl;
    Participant p11("germany","song_germany",143,"singer_germany");
    cout<<p11<<endl;
    Participant p12("slovenia","song_slovenia",207,"singer_slovenia");
    cout<<p12<<endl;
    Participant p13("uk","song_uk",201,"singer_uk");
    cout<<p13<<endl;
    Participant p14("latvia","song_latvia",180,"singer_latvia");
    cout<<p14<<endl;
    Participant p15("hungary","song_hungary",124,"singer_hungary");
    cout<<p15<<endl;
    Participant p16("belgium","song_belgium",187,"singer_belgium");
    cout<<p16<<endl;
    Participant p17("andora","song_andora",172,"singer_andora");
    cout<<p17<<endl;
    Participant p18("croatia","song_croatia",157,"singer_croatia");
    cout<<p18<<endl;
    Participant p19("bosnia","song_bosnia",128,"singer_bosnia");
    cout<<p19<<endl;
    Participant p20("cyrpus","song_cyrpus",198,"singer_cyrpus");
    cout<<p20<<endl;
    Participant p21("latvia","song_latvia",106,"singer_latvia");
    cout<<p21<<endl;
    Participant p22("greece","song_greece",194,"singer_greece");
    cout<<p22<<endl;
    Participant p23("germany","song_germany",119,"singer_germany");
    cout<<p23<<endl;
    Participant p24("lithiania","song_lithiania",186,"singer_lithiania");
    cout<<p24<<endl;
    Participant p25("germany","song_germany",114,"singer_germany");
    cout<<p25<<endl;
    Participant p26("croatia","song_croatia",168,"singer_croatia");
    cout<<p26<<endl;
    Participant p27("norway","song_norway",163,"singer_norway");
    cout<<p27<<endl;
    Participant p28("spain","song_spain",112,"singer_spain");
    cout<<p28<<endl;
    Participant p29("uk","song_uk",216,"singer_uk");
    cout<<p29<<endl;
    Participant p30("georgia","song_georgia",159,"singer_georgia");
    cout<<p30<<endl;
    Participant p31("russia","song_russia",217,"singer_russia");
    cout<<p31<<endl;
    Participant p32("norway","song_norway",188,"singer_norway");
    cout<<p32<<endl;
    Participant p33("moldova","song_moldova",137,"singer_moldova");
    cout<<p33<<endl;
    Participant p34("bulgaria","song_bulgaria",113,"singer_bulgaria");
    cout<<p34<<endl;
    Participant p35("spain","song_spain",176,"singer_spain");
    cout<<p35<<endl;
    Participant p36("latvia","song_latvia",191,"singer_latvia");
    cout<<p36<<endl;
    p33.update("new_song",0,"");
    p29.update("new_song",0,"");
    p17.update("new_song",0,"");
    p33.update("new_song",0,"");
    p18.update("new_song",0,"newsinger");
    p19.update("new_song",0,"newsinger");
    p33.update("new_song",0,"newsinger");
    p7.update("new_song",0,"newsinger");
    p8.update("new_song",119,"newsinger");
    p19.update("new_song",153,"newsinger");
    p25.update("new_song",170,"newsinger");
    p11.update("new_song",175,"newsinger");
    cout<<eurovision<<endl;
    eurovision+=p30;
    eurovision+=p21;
    eurovision+=p28;
    eurovision+=p15;
    eurovision+=p16;
    eurovision+=p24;
    eurovision+=p24;
    eurovision+=p11;
    eurovision+=p25;
    eurovision+=p23;
    eurovision+=p11;
    eurovision+=p33;
    eurovision+=p4;
    eurovision+=p25;
    cout<<eurovision<<endl;
    eurovision+=p4;
    eurovision-=p9;
    eurovision+=p1;
    eurovision-=p33;
    eurovision+=p15;
    eurovision-=p18;
    eurovision-=p22;
    eurovision-=p4;
    eurovision-=p20;
    eurovision-=p14;
    eurovision+=p21;
    eurovision-=p19;
    eurovision-=p35;
    eurovision-=p17;
    eurovision+=p15;
    eurovision-=p10;
    eurovision-=p3;
    eurovision+=p4;
    eurovision+=p6;
    eurovision-=p13;
    eurovision+=p34;
    eurovision-=p28;
    eurovision-=p12;
    eurovision-=p24;
    cout<<eurovision<<endl;
    (((((eurovision+=p32)-=p32)-=p36)-=p14)+=p11)-=p36;
    MainControl::Iterator i;
    for (i = eurovision.begin(); i<eurovision.end(); ++i)
        cout << *i << endl;
    for (i = eurovision.begin(); !(i==eurovision.end()); ++i)
        cout << *i << endl;
    eurovision.setPhase(Contest);
    eurovision.setPhase(Voting);
    eurovision.participate("slovakia");
    eurovision.participate("bulgaria");
    eurovision.participate("luxembourg");
    eurovision.participate("slovenia");
    eurovision.participate("france");
    eurovision.participate("andora");
    eurovision.participate("russia");
    eurovision.participate("serbia");
    eurovision.participate("italy");
    eurovision.participate("armenia");
    eurovision.participate("spain");
    eurovision.participate("hungary");
    eurovision.participate("armenia");
    eurovision.participate("hungary");
    p18.update("",120,"");
    cout<<p18<<endl;
    p18.update("",120,"");
    cout<<p18<<endl;
    p25.update("",120,"");
    cout<<p25<<endl;
    p14.update("",120,"");
    cout<<p14<<endl;
    p11.update("",120,"");
    cout<<p11<<endl;
    p1.update("",120,"");
    cout<<p1<<endl;
    p14.update("",120,"");
    cout<<p14<<endl;
    p11.update("",120,"");
    cout<<p11<<endl;
    p9.update("",120,"");
    cout<<p9<<endl;
    p2.update("",120,"");
    cout<<p2<<endl;
    p15.update("",120,"");
    cout<<p15<<endl;
    p30.update("",120,"");
    cout<<p30<<endl;
    p8.update("",120,"");
    cout<<p8<<endl;
    p34.update("",120,"");
    cout<<p34<<endl;
    Voter v1("israel",Judge);
    Voter v2("turkey",Judge);
    Voter v3("malta",Judge);
    Voter v4("greece",Regular);
    Voter v5("moldova");
    Voter v6("andora",Regular);
    Voter v7("belgium",Regular);
    Voter v8("france",Judge);
    Voter v9("austria",Judge);
    Voter v10("latvia",Judge);
    Voter v11("uk",Judge);
    Voter v12("belarus",Judge);
    Voter v13("croatia");
    Voter v14("france");
    Voter v15("andora");
    Voter v16("norway");
    Voter v17("andora",Judge);
    Voter v18("lithiania");
    Voter v19("russia");
    Voter v20("andora");
    Voter v21("france",Regular);
    Voter v22("germany",Judge);
    Voter v23("latvia");
    Voter v24("uk",Judge);
    Voter v25("malta",Regular);
    Voter v26("belarus",Judge);
    Voter v27("luxembourg",Regular);
    Voter v28("france",Regular);
    Voter v29("belgium",Judge);
    Voter v30("malta",Regular);
    Voter v31("turkey",Regular);
    Voter v32("norway",Judge);
    Voter v33("malta");
    Voter v34("armenia",Regular);
    Voter v35("belgium",Regular);
    Voter v36("croatia");
    Voter v37("spain",Regular);
    Voter v38("cyrpus",Regular);
    Voter v39("netherlands");
    Voter v40("latvia");
    Voter v41("sweden");
    Voter v42("serbia");
    Voter v43("bosnia");
    Voter v44("belarus",Regular);
    Voter v45("kazakhastan",Judge);
    Voter v46("spain",Judge);
    Voter v47("kazakhastan",Judge);
    Voter v48("austria",Regular);
    Voter v49("bulgaria",Judge);
    Voter v50("ukraine");
    Voter v51("israel");
    Voter v52("bulgaria",Regular);
    Voter v53("georgia");
    Voter v54("hungary");
    Voter v55("latvia",Regular);
    Voter v56("turkey",Regular);
    Voter v57("austria",Judge);
    Voter v58("georgia");
    Voter v59("bulgaria",Judge);
    Voter v60("belarus",Judge);
    Voter v61("russia",Judge);
    Voter v62("slovakia",Judge);
    Voter v63("belarus",Regular);
    Voter v64("austria",Judge);
    Voter v65("latvia");
    Voter v66("greece",Judge);
    Voter v67("france");
    Voter v68("hungary");
    Voter v69("spain");
    Voter v70("sweden");
    Voter v71("uk");
    Voter v72("italy");
    Voter v73("estonia");
    Voter v74("turkey",Regular);
    Voter v75("italy",Judge);
    Voter v76("luxembourg");
    Voter v77("andora",Judge);
    Voter v78("slovakia",Regular);
    Voter v79("greece",Judge);
    Voter v80("israel",Regular);
    Voter v81("estonia",Regular);
    Voter v82("slovakia",Regular);
    Voter v83("greece",Regular);
    Voter v84("latvia",Judge);
    Voter v85("andora",Regular);
    Voter v86("luxembourg");
    Voter v87("serbia");
    Voter v88("sweden");
    Voter v89("armenia");
    Voter v90("israel",Judge);
    Voter v91("turkey");
    Voter v92("estonia");
    Voter v93("ireland");
    Voter v94("uk",Regular);
    Voter v95("andora",Regular);
    Voter v96("georgia",Judge);
    Voter v97("serbia",Judge);
    Voter v98("greece");
    Voter v99("turkey");
    cout<<eurovision<<endl;
    eurovision+=Vote(v6,"austria");
    eurovision+=Vote(v55,"croatia");
    eurovision+=Vote(v87,"austria");
    eurovision+=Vote(v33,"croatia");
    eurovision+=Vote(v32,"france","austria","moldova","luxembourg","kazakhastan","germany","belgium","russia","armenia");
    eurovision+=Vote(v26,"bulgaria","norway","france");
    eurovision+=Vote(v45,"croatia","lithiania","spain","bulgaria","russia","austria");
    eurovision+=Vote(v65,"switzerland");
    eurovision+=Vote(v49,"moldova","belgium","turkey","bosnia","austria","italy");
    eurovision+=Vote(v16,"italy");
    eurovision+=Vote(v46,"estonia","norway","germany","italy","malta","andora","bosnia");
    eurovision+=Vote(v42,"belarus");
    eurovision+=Vote(v70,"bosnia");
    eurovision+=Vote(v84,"kazakhastan","moldova","hungary","belarus","ukraine");
    eurovision+=Vote(v14,"norway");
    eurovision+=Vote(v38,"serbia");
    eurovision+=Vote(v10,"hungary","kazakhastan","bulgaria","russia","lithiania","estonia","andora","slovakia","moldova");
    eurovision+=Vote(v26,"bosnia");
    eurovision+=Vote(v33,"sweden");
    eurovision+=Vote(v75,"turkey","sweden","georgia");
    eurovision+=Vote(v1,"georgia","ireland","spain","hungary","turkey");
    eurovision+=Vote(v73,"italy");
    eurovision+=Vote(v85,"kazakhastan");
    eurovision+=Vote(v7,"armenia");
    eurovision+=Vote(v49,"sweden","slovakia","malta","bosnia","armenia");
    eurovision+=Vote(v96,"norway","russia","bulgaria","italy","georgia","israel","hungary","estonia");
    eurovision+=Vote(v84,"armenia");
    eurovision+=Vote(v50,"ireland");
    eurovision+=Vote(v47,"france","croatia","germany","spain","andora","russia","austria");
    eurovision+=Vote(v65,"italy");
    eurovision+=Vote(v56,"greece");
    eurovision+=Vote(v88,"andora");
    eurovision+=Vote(v70,"russia");
    eurovision+=Vote(v75,"france","spain","kazakhastan","ukraine");
    eurovision+=Vote(v61,"latvia","netherlands","estonia","andora","switzerland","slovenia");
    eurovision+=Vote(v94,"slovenia");
    eurovision+=Vote(v55,"luxembourg");
    eurovision+=Vote(v10,"germany","belarus","malta","cyrpus","latvia");
    eurovision+=Vote(v80,"hungary");
    eurovision+=Vote(v69,"moldova");
    eurovision+=Vote(v37,"malta");
    eurovision+=Vote(v45,"armenia","cyrpus","turkey","belarus","switzerland","france","croatia","italy","norway");
    eurovision+=Vote(v31,"cyrpus");
    eurovision+=Vote(v65,"germany");
    eurovision+=Vote(v38,"kazakhastan");
    eurovision+=Vote(v68,"cyrpus");
    eurovision+=Vote(v92,"kazakhastan");
    eurovision+=Vote(v5,"estonia");
    eurovision+=Vote(v61,"greece","sweden","turkey","france","croatia","bosnia","netherlands","malta","italy","israel");
    eurovision+=Vote(v44,"spain");
    eurovision+=Vote(v87,"andora");
    eurovision+=Vote(v57,"slovenia","andora");
    eurovision+=Vote(v84,"belgium","slovakia");
    eurovision+=Vote(v69,"italy");
    eurovision+=Vote(v10,"ireland","norway");
    eurovision+=Vote(v77,"hungary","turkey","austria");
    eurovision+=Vote(v27,"ireland");
    eurovision+=Vote(v57,"switzerland","netherlands","andora");
    eurovision+=Vote(v31,"france");
    eurovision+=Vote(v42,"kazakhastan");
    eurovision+=Vote(v55,"malta");
    eurovision+=Vote(v96,"belgium","israel","hungary","kazakhastan","serbia","moldova");
    eurovision+=Vote(v4,"luxembourg");
    eurovision+=Vote(v70,"andora");
    eurovision+=Vote(v89,"cyrpus");
    eurovision+=Vote(v77,"armenia");
    eurovision+=Vote(v85,"spain");
    eurovision+=Vote(v35,"luxembourg");
    eurovision+=Vote(v76,"ireland");
    eurovision+=Vote(v51,"malta");
    eurovision+=Vote(v12,"netherlands","latvia","lithiania","georgia","russia","luxembourg","slovakia","estonia","spain");
    eurovision+=Vote(v63,"russia");
    eurovision+=Vote(v45,"luxembourg","turkey","germany","israel","estonia");
    eurovision+=Vote(v3,"israel","luxembourg","cyrpus","turkey","germany","ukraine","moldova");
    eurovision+=Vote(v67,"malta");
    eurovision+=Vote(v65,"turkey");
    eurovision+=Vote(v76,"russia");
    eurovision+=Vote(v79,"ireland","israel","spain","ukraine","italy");
    eurovision+=Vote(v55,"serbia");
    eurovision+=Vote(v63,"russia");
    eurovision+=Vote(v47,"ukraine","bosnia","malta","italy","hungary","switzerland","georgia","lithiania");
    eurovision+=Vote(v14,"serbia");
    eurovision+=Vote(v65,"turkey");
    eurovision+=Vote(v23,"belarus");
    eurovision+=Vote(v6,"croatia");
    eurovision+=Vote(v85,"andora");
    eurovision+=Vote(v22,"russia","belgium","switzerland","spain","croatia","italy","armenia","germany","ireland");
    eurovision+=Vote(v2,"ukraine","italy","slovenia","moldova","kazakhastan");
    eurovision+=Vote(v75,"lithiania","italy","switzerland","turkey");
    eurovision+=Vote(v83,"austria");
    eurovision+=Vote(v8,"ukraine","spain");
    eurovision+=Vote(v37,"norway");
    eurovision+=Vote(v5,"norway");
    eurovision+=Vote(v78,"norway");
    eurovision+=Vote(v55,"norway");
    eurovision+=Vote(v5,"kazakhastan");
    eurovision+=Vote(v94,"bosnia");
    eurovision+=Vote(v45,"italy","ireland");
    eurovision+=Vote(v86,"norway");
    eurovision+=Vote(v35,"latvia");
    eurovision+=Vote(v66,"moldova","croatia","lithiania");
    eurovision+=Vote(v23,"latvia");
    eurovision+=Vote(v74,"andora");
    eurovision+=Vote(v24,"estonia","kazakhastan","latvia","switzerland");
    eurovision+=Vote(v38,"estonia");
    eurovision+=Vote(v21,"belarus");
    eurovision+=Vote(v90,"russia","estonia","france","netherlands","armenia");
    eurovision+=Vote(v58,"belarus");
    eurovision+=Vote(v8,"france","andora","latvia","hungary","moldova");
    eurovision+=Vote(v69,"luxembourg");
    eurovision+=Vote(v88,"croatia");
    eurovision+=Vote(v27,"estonia");
    eurovision+=Vote(v81,"kazakhastan");
    eurovision+=Vote(v72,"croatia");
    eurovision+=Vote(v18,"ireland");
    eurovision+=Vote(v25,"bulgaria");
    eurovision+=Vote(v34,"croatia");
    eurovision+=Vote(v64,"italy","armenia","georgia","hungary");
    eurovision+=Vote(v35,"cyrpus");
    eurovision+=Vote(v46,"germany","kazakhastan","malta","andora","moldova","georgia","estonia","slovenia","bulgaria");
    eurovision+=Vote(v86,"france");
    eurovision+=Vote(v17,"kazakhastan","malta","sweden","russia","germany","netherlands","luxembourg");
    eurovision+=Vote(v59,"serbia","cyrpus","lithiania","latvia","spain","sweden");
    eurovision+=Vote(v30,"lithiania");
    eurovision+=Vote(v63,"luxembourg");
    eurovision+=Vote(v43,"france");
    eurovision+=Vote(v58,"malta");
    eurovision+=Vote(v62,"germany","luxembourg","turkey","estonia");
    eurovision+=Vote(v93,"malta");
    eurovision+=Vote(v34,"turkey");
    eurovision+=Vote(v66,"turkey","slovenia","luxembourg","germany","moldova","lithiania","armenia","serbia","italy");
    eurovision+=Vote(v74,"estonia");
    eurovision+=Vote(v79,"malta","turkey","croatia","lithiania");
    eurovision+=Vote(v61,"serbia","luxembourg","georgia");
    eurovision+=Vote(v48,"latvia");
    eurovision+=Vote(v31,"greece");
    eurovision+=Vote(v45,"lithiania");
    eurovision+=Vote(v77,"spain","russia","israel","moldova");
    eurovision+=Vote(v69,"georgia");
    eurovision+=Vote(v43,"cyrpus");
    eurovision+=Vote(v30,"malta");
    eurovision+=Vote(v33,"andora");
    eurovision+=Vote(v18,"hungary");
    eurovision+=Vote(v70,"slovenia");
    eurovision+=Vote(v10,"hungary","cyrpus","kazakhastan");
    eurovision+=Vote(v8,"malta");
    eurovision+=Vote(v74,"slovenia");
    eurovision+=Vote(v26,"croatia","belgium","italy","serbia","cyrpus","latvia","kazakhastan","spain","lithiania","israel");
    eurovision+=Vote(v47,"turkey","israel","netherlands","armenia","cyrpus");
    eurovision+=Vote(v6,"greece");
    eurovision+=Vote(v89,"serbia");
    eurovision+=Vote(v85,"estonia");
    eurovision+=Vote(v31,"serbia");
    eurovision+=Vote(v93,"estonia");
    eurovision+=Vote(v50,"switzerland");
    eurovision+=Vote(v31,"georgia");
    eurovision+=Vote(v61,"greece","moldova","andora","cyrpus","austria","serbia","sweden","belarus");
    eurovision+=Vote(v33,"belgium");
    eurovision+=Vote(v10,"kazakhastan","belgium","croatia","lithiania","ukraine","russia");
    eurovision+=Vote(v72,"turkey");
    eurovision+=Vote(v26,"bosnia","latvia","estonia","israel","germany","kazakhastan","netherlands");
    eurovision+=Vote(v12,"austria","moldova","lithiania","slovakia","switzerland","latvia","armenia","bosnia","turkey");
    eurovision+=Vote(v33,"luxembourg");
    eurovision+=Vote(v94,"ireland");
    eurovision+=Vote(v20,"norway");
    eurovision+=Vote(v24,"germany","malta","israel");
    eurovision+=Vote(v54,"austria");
    eurovision+=Vote(v72,"estonia");
    eurovision+=Vote(v5,"slovenia");
    eurovision+=Vote(v55,"sweden");
    eurovision+=Vote(v28,"austria");
    eurovision+=Vote(v20,"norway");
    eurovision+=Vote(v80,"spain");
    eurovision+=Vote(v94,"spain");
    eurovision+=Vote(v26,"latvia","greece","bulgaria","turkey","armenia","switzerland","belgium");
    eurovision+=Vote(v78,"greece");
    eurovision+=Vote(v53,"latvia");
    eurovision+=Vote(v12,"germany","lithiania","israel","latvia");
    eurovision+=Vote(v97,"sweden","slovenia","estonia","belgium");
    eurovision+=Vote(v49,"estonia","slovakia","latvia","switzerland","slovenia","israel","lithiania","cyrpus","belarus");
    eurovision+=Vote(v81,"georgia");
    eurovision+=Vote(v78,"austria");
    eurovision+=Vote(v85,"sweden");
    eurovision+=Vote(v3,"hungary","italy");
    eurovision+=Vote(v12,"andora","kazakhastan","ukraine");
    eurovision+=Vote(v67,"armenia");
    eurovision+=Vote(v41,"spain");
    eurovision+=Vote(v99,"italy");
    eurovision+=Vote(v62,"hungary");
    eurovision+=Vote(v89,"malta");
    eurovision+=Vote(v72,"moldova");
    eurovision+=Vote(v91,"norway");
    eurovision+=Vote(v52,"armenia");
    eurovision+=Vote(v90,"kazakhastan","hungary","turkey","moldova","armenia");
    eurovision+=Vote(v24,"belgium","georgia","sweden");
    eurovision+=Vote(v50,"italy");
    eurovision+=Vote(v36,"israel");
    eurovision+=Vote(v85,"bosnia");
    eurovision+=Vote(v43,"luxembourg");
    p23.update("shouldnot",143,"error");
    cout<<p23<<endl;
    p31.update("shouldnot",143,"error");
    cout<<p31<<endl;
    p19.update("shouldnot",143,"error");
    cout<<p19<<endl;
    p14.update("shouldnot",143,"error");
    cout<<p14<<endl;
    p30.update("shouldnot",143,"error");
    cout<<p30<<endl;
    p24.update("shouldnot",143,"error");
    cout<<p24<<endl;
    p9.update("shouldnot",143,"error");
    cout<<p9<<endl;
    p30.update("shouldnot",143,"error");
    cout<<p30<<endl;
    p14.update("shouldnot",143,"error");
    cout<<p14<<endl;
    p2.update("shouldnot",143,"error");
    cout<<p2<<endl;
    p27.update("shouldnot",143,"error");
    cout<<p27<<endl;
    p9.update("shouldnot",143,"error");
    cout<<p9<<endl;
    p20.update("shouldnot",143,"error");
    cout<<p20<<endl;
    p34.update("shouldnot",143,"error");
    cout<<p34<<endl;
    cout<<eurovision<<endl;
    cout<<eurovision(1,Regular)<<endl;
    cout<<eurovision(2,Regular)<<endl;
    cout<<eurovision(3,Regular)<<endl;
    cout<<eurovision(4,Regular)<<endl;
    cout<<eurovision(5,Regular)<<endl;
    cout<<eurovision(6,Regular)<<endl;
    cout<<eurovision(7,Regular)<<endl;
    cout<<eurovision(8,Regular)<<endl;
    cout<<eurovision(9,Regular)<<endl;
    cout<<eurovision(10,Regular)<<endl;
    cout<<eurovision(1,Judge)<<endl;
    cout<<eurovision(2,Judge)<<endl;
    cout<<eurovision(3,Judge)<<endl;
    cout<<eurovision(4,Judge)<<endl;
    cout<<eurovision(5,Judge)<<endl;
    cout<<eurovision(6,Judge)<<endl;
    cout<<eurovision(7,Judge)<<endl;
    cout<<eurovision(8,Judge)<<endl;
    cout<<eurovision(9,Judge)<<endl;
    cout<<eurovision(10,Judge)<<endl;
    cout<<eurovision(1,All)<<endl;
    cout<<eurovision(2,All)<<endl;
    cout<<eurovision(3,All)<<endl;
    cout<<eurovision(4,All)<<endl;
    cout<<eurovision(5,All)<<endl;
    cout<<eurovision(6,All)<<endl;
    cout<<eurovision(7,All)<<endl;
    cout<<eurovision(8,All)<<endl;
    cout<<eurovision(9,All)<<endl;
    cout<<eurovision(10,All)<<endl;
    cout<<eurovision<<endl;

}